### ISSUE TITLE
Не работает скрипт dl.php?

### ISSUE THREAD

**Issue by SashkaPro** [prog-it/Asterisk-CDR-Viewer-Mod#1]
Приветствую!

Начинаю тестировать, и не работает скачивание файлов.
Оговорка: у меня файлы размещаются в /monitor/$uniqueid.ogg

Все ссылки в ACVM в столбике "Файл" идут с зелеными стрелками (а-ля файл есть), но при этом при наведении на них - запрашивается пустой URL: http://url/v2/dl.php?f=
А я так понимаю, что по дефолту, он должен спрашивать "dl.php?f=$fname.

Вопросы:
а) Должен ли урл по дефолту быть пустым (dl.php?f=) ?
б) Как сделать, что бы он запрашивал $uniqueid? Вариант замены в inc/func.inc.php
строки         
$recorded_file = $row['filename'];
на строку
"$recorded_file = glob($system_monitor_dir . '/*' . $row['uniqueid'] . '.' . $system_audio_format); " 
не взлетел.

**Comment by prog-it** [comment]
Здравствуйте. Вы хорошо прочитали Readme.txt ? Настроили параметры в конфиге ? 

У меня файлы хранятся в таком виде:
Сегодняшние звонки в /calls, затем скрипт их переносит по папкам, звонки за другие даты в папках вида calls\2015\2015-01\2015-01-01. 

Вы почти правы, скрипту dl.php передается путь к файлу в base64 (dl.php?f=ZmlsZW5hbWUubXAz). Пример в раскодированном виде: Звонок сегодня: dl.php?f=filename.mp3, звонок за прошедшую дату: dl.php?f=2015/2015-01/2015-01-01/filename.mp3

URL пустым быть не должен, если файл не существует, то будет отображена соответствующая иконка. У вас показывается кнопка для скачивания (со стрелкой вниз), покалучается скачать файл (не прослушать) ?

Не совесм понятно насчет $uniqueid...

В каком виде у вас будут храниться файлы, за все даты в одной папке ? Скопируйте и напишите здесь точную ссылку на скачивание какого-либо файла (без домена), а лучше сделайте пару скринов, какие кнопки в столбце "файл оторажаются".

**Comment by SashkaPro** [comment]
Можно и с доменом. :)

Смотрите:

Скрин: http://pixs.ru/showimage/Snimokekra_3578916_18016104.png

URL ACVM: http://asterisk/v2/
URL папки с файлами http://asterisk/monitor/
Пример URL'а с файлом*: http://asterisk/monitor/1436793403.18.ogg

То есть, в CDR-таблице есть столбец Userfield, мне бы как-нибудь брать значение этого поля, добавлять расширение .ogg и отдавать такой файл на скачивание...
В обычном CDR-Viewer'е все так и есть, а тут что-то сообразить не могу..

* - не важно за какую дату файл, все файлы хранятся в одной папке, и обзываются Userfield / uniqueid разговора.

**Comment by SashkaPro** [comment]
В общем, я конечно добился URL'а вида http://asterisk/v2/dl.php?f=1436791610.12662.ogg (и соответственно скачивания файла), но, очень уж костыльным способом.

Хотелось бы вариант скрипта который из коробки позволит задавать путь и расширение файла...

Готов тестить, если у вас есть желание. :)

**Comment by prog-it** [comment]
Не нужно никаких "костыльных способов", все настраивается в конфиге. Расширение - $system_audio_format, путь - $system_monitor_dir.

Совсем другое дело, что здесь отличается логика хранения файлов, распределение по папкам в соответствии с датой, так намного удобнее. Имя файла, кстати, пишется не в userfield, а в отдельный столбец, благодаря чему userfield можно использовать для др. целей. Обо всем этом написано в readme.txt.

Может проще настроить один раз распределение по папкам ? Или вам удобнее, чтобы записи разговоров хранились за все даты в одной папке ? Напишите свое мнение.

Чтобы сделать примерно, как вы хотите, потребуется модифицировать скрипт.

**Comment by SashkaPro** [comment]
Во-от!
Здесь логика другая, стандартный CDR Viewer использует логику которую описал я.
В принципе, для текущих инсталляций я решение нашел, следующие - попробую сделать с уклоном на вашу логику. То есть, переделывать из-за меня конкретно ничего не надо.

Если честно, был бы признателен за версию extensions.conf (не-AEL формата).

Будем тестить дальше.

**Comment by prog-it** [comment]
Попробуйте сделать с новым форматом хранения по папкам, в readme.txt довольно подробно написано. Если что, пишите.
Я могу конечно сделать, чтобы в конфиге можно было задать поле БД, откуда будет брать имя файла, также настройку, чтоб все файлы были в одной папке. Но пока просто не вижу смысла, это не удобно, как мне кажется.
На счет extensions.conf, скоро, скорее всего завтра, добавлю пример в readme.txt. 
У меня сначала был простой диалплан и можно было обойтись extensions.conf, но теперь все в extensions.ael, есть еще extensions.lua))

**Comment by prog-it** [comment]
Добавил пример для extensions.conf. Посмотрите обновленный Readme.txt.

**Comment by prog-it** [comment]
Исправил баг о котором вы писали в самом первом сообщении, а именно пустой url dl.php?f=. Если поле filename было пустое, то показывало пустой url. У меня данный баг не проявлялся, т.к. в столбце filename задано значение по умолчанию none. 
Обновите файл func.inc.php.

**Comment by SashkaPro** [comment]
Огонь, работает!

1) dl.php показывает корректно урл (даже если файлнейм пустой) (точнее иконку, что записи нет)
2) файлы записи работают! :+1: 

Сейчас, получается полный порядок.

Еще вопрос - а например плеер поменять? Сейчас смотрите, клац по "плей", всплывает окно, слова клац по "плей". То есть  даблклац, может оптимизировать?

**Comment by prog-it** [comment]
Нормального плеера пока нет, uppod самый оптимальный вариант. Я перебрал все плееры какие только есть. Хотелось бы html5 плеер, без флеша, но корректно и воспроизводит только флеш. Тег audio тоже не вариант, какой браузер воспроизводит, а какой нет(например хром).

Не совсем понял на счет дабл клик... Напишите подробнее. Вы имеете ввиду, чтобы после всплывающиего окна сразу шло автовоспроизведение файла ?

**Comment by SashkaPro** [comment]
Именно!
А еще, можно (раз экран при вызове плеера затемняется) - писать какие-нибудь опознавательные знаки (дата/время звонка), чтоб если по запарке переключился на соседнюю вкладку, вернулся - и понял, что же ты слушал только что. :)

**Comment by prog-it** [comment]
Добавил, пробуйте. Обновите скрипт, config.inc.php можно оставить старый.

**Comment by SashkaPro** [comment]
Работает, плеер стартует сразу же.

Еще пожелание можно? :)

Вот сегодня 15 июля, за сегодня у меня звонков нет. И когда я клацаю кнопку "найти" у меня страница просто рефрешится (ну точнее, он а-ля "ищет, ничего не находит, ничего не показывает").

Можно ли сделать, что бы когда "результатов 0" - он писал что-нибудь из серии "Результатов по указанным условиям не найдено" ?
Было бы удобней. А то я обновил, тыкаю поиск, и не понимаю, то ли к базе соединения нет, то ли скрипт не работает.. :)

**Comment by SashkaPro** [comment]
Еще, не знаю, на сколько клевое предложение, но вот есть столбец "Описание" (которы в свою очередь берется из userfield).
Может сделать там "мини редактор", в который можно вводить текст, который в свою очередь будет писаться в этот самый userfield?
Знаете как у свежих phpmyadmin'ов, без рефрешей, без переходов по страницам, ткнули на поле - появилось поле, в него можно заполнить значение.

Поясню смысл:
К примеру, звонок 2015-07-14 19:45:45, и в "описание" пишем - "угроза жизни и здоровья менеджеру"
И все, потом скроллом взяли и сразу нашли интересующий нас звонок.

Помоему, полезно было бы. :)
Может быть, это можно было бы в качестве плагина запилить, ибо полюбому не всем нужно... Наверное.

**Comment by prog-it** [comment]
На счет того, чтобы писало "Результатов не найдено", сделаем.

На счет поля "Описание". Что писать в это поле можно настроить в диалплане. Например, у меня скрипт обрабатывает входящие звонки, есть Ночной режим (звонки 00.00-8.00 не проходят), есть Черный список. Так вот если позвонил номер из черного списка у меня в это поле пишется соответствующее сообщение, тоже самое и с Ночным режимом. Потом при просмотре звонков сразу понятно, кто звонил.

Пока не могу понять для чего может пригодиться самим вводить "Описание". Мне кажется, в это поле должен писать только Asterisk.

**Comment by SashkaPro** [comment]
Согласен. Я уже даже придумал...
В описание можно писать имя контекста на который свалился звонок, то есть, к примеру,
если звонок приходит на 8-800-555-555-0 то можно писать userfield=8-800, и будем понимать, куда прилетел звонок...
Спасибо за мысль.

**Comment by prog-it** [comment]
У вас появляются высплывающие подсказки при наведении, допустим на "Статус" ?
Так вот, если навести курсор на "Номер назначения", то появится всплывающая подсказка с названием контекста. Попробуйте.
Вы кстати написали (звонок приходит на 8-800-555-555-0 то можно писать userfield=8-800) не о контексте, а об экстеншене. :)

**Comment by SashkaPro** [comment]
Наводить не совсем удобно, если нужно нужно в дальнейшем отсортировать звонки.
Но да, тоже вариант. :)

**Comment by prog-it** [comment]
В базу и так пишется Название кентекста, чтобы не писать дваждыв в userfield, то можно поправить в скрипте. что выводить в поле Описание. Подсказка: в index.php заменить formatUserField($row['userfield']); на то, что нужно выводить в Описание.

**Comment by prog-it** [comment]
Посмотрел код на счет того, чтобы писало "Результатов не найдено". Не вижу особого смысла в этом, т.к. если соединения с базой не будет или еще какая-либо ошибка, то выдаст соотвествующее сообщение. А так слишком много нужно переделывать.

**Comment by prog-it** [comment]
Не нашли еще какие-либо баги ? Если нет, то закрываю ветку (close issue).

**Comment by SashkaPro** [comment]
Ок, если что - напишу отдельный ищью.
