### ISSUE TITLE
Не отображаются иконки востпроизведения/скачивания разговоров

### ISSUE THREAD

**Issue by otrazhenie-q** [prog-it/Asterisk-CDR-Viewer-Mod#120]
Доброго дня.
никак не могу добиться отображения иконок записей разговоров в панели. 
При наведении мыши на строку курсор меняется и можно прослушать или скачать запись.
Как добиться отображения иконок?

**Comment by otrazhenie-q** [comment]
да! в логах ругается на строку 459 файла index.php

**Comment by prog-it** [comment]
Раскомментируйте в файле index.php самую первую строку, что после этого будет выдавать на странице.

**Comment by otrazhenie-q** [comment]
ругается за временную зону


>Пятница,  7 декабря 2018, 11:42 +03:00 от prog-it <notifications@github.com>:
>
>Раскомментируйте в файле index.php самую первую строку, что после этого будет выдавать на странице.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
q q

**Comment by otrazhenie-q** [comment]
Notice: Undefined index: id in /var/www/asterisk-cdr-viewer/index.php on line 459
вот еще что выдает

**Comment by prog-it** [comment]
Создайте в базе столбец с id (автоинкремент), тогда все должно работать. Об этом есть в файле справки.

**Comment by otrazhenie-q** [comment]
столбец создал. Ошибка ушла. Иконок нет. В логах пусто.
Откуда он берет иконки?


>Пятница,  7 декабря 2018, 16:59 +03:00 от prog-it <notifications@github.com>:
>
>Создайте в базе столбец с id (автоинкремент), тогда все должно работать. Об этом есть в файле справки.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
q q

**Comment by prog-it** [comment]
Иконки находятся в папке img. SVG файлы

**Comment by otrazhenie-q** [comment]
файлы на месте.
файрфокс не хочет их отображать. Опера тоже.

>Понедельник, 10 декабря 2018, 15:53 +03:00 от prog-it <notifications@github.com>:
>
>Иконки находятся в папке img. SVG файлы
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
q q

**Comment by prog-it** [comment]
Либо веб-сервер неправильно отдает статику, либо что-то с браузерами (что маловероятно).
Попробуйте напрямую обратиться в браузере к какой-либо иконке, например: http://example.com/img/record_play.svg

**Comment by otrazhenie-q** [comment]
Думаю дело в апаче.
указываю прямую ссылку на иконку - выдает содержимое текстом.

вот как заставить апач выдавать картинку?


>Понедельник, 10 декабря 2018, 16:18 +03:00 от prog-it <notifications@github.com>:
>
>Либо веб-сервер неправильно отдает статику, либо что-то с браузерами (что маловероятно).
>Попробуйте напрямую обратиться в браузере к какой-либо иконке, например:  http://example.com/img/record_play.svg
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
q q

**Comment by otrazhenie-q** [comment]
Победил!
убрал из svg файлов параметры version и id
иконки стали отображаться!
может кому пригодится....

>Понедельник, 10 декабря 2018, 16:18 +03:00 от prog-it <notifications@github.com>:
>
>Либо веб-сервер неправильно отдает статику, либо что-то с браузерами (что маловероятно).
>Попробуйте напрямую обратиться в браузере к какой-либо иконке, например:  http://example.com/img/record_play.svg
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
q q

**Comment by prog-it** [comment]
В каких браузерах проверяли? Напишите браузер и его версию.
Проверил в каких возможно браузерах, все отлично работает.

**Comment by prog-it** [comment]
В новой версии будет исправлено.

**Comment by otrazhenie-q** [comment]
проверяю в firefox 60.2.2esr, Яндекс Браузер.
иконки стали отображаться, кроме иконки воспроизведения.
Пока не могу понять, в чем разница между ней и остальными.

**Comment by otrazhenie-q** [comment]
все заработало. мой косяк был.
теперь все иконки отображаются.
тему можно закрывать.
