### ISSUE TITLE
Экспорт в CSV

### ISSUE THREAD

**Issue by AstutusLoki** [prog-it/Asterisk-CDR-Viewer-Mod#124]
Здравствуйте.

Пытаюсь сделать выгрузку в CSV, на выходе получаю пустой файл.
В самой директории, куда складывается файл, он тоже пустой.

**Comment by prog-it** [comment]
Раскомментируйте самую первую строчку в файлe index.php. Какие после этого выведет сообщения об ошибках на странице.

**Comment by AstutusLoki** [comment]
Спасибо
Вопрос не актуален - проблема была в отсутствии свободного места
