### ISSUE TITLE
Нет записи в столбец filename

### ISSUE THREAD

**Issue by DItPromoil** [prog-it/Asterisk-CDR-Viewer-Mod#13]
У нас  идет подключение к MySQL через ODBC.
И никак не можем сделать так, чтоб Asterisk знал о существовании этого столбца в таблице.

**Comment by prog-it** [comment]
Прочитайте хорошо Readme. Скрее всего это, выдержка из Readme ниже. Если получится, отпишитесь.
====
Для того, чтобы Asterisk смог взаимодействовать с новыми столбцами в таблице, необходимо в файле cdr_mysql.conf создать их алиасы. Добавим в конец этого файла ( секция [columns] ) строчки: alias realdst => realdst alias название_столбца => название_столбца Вместо "название_столбца" вставьте название столбца, в котором хранится название записи звонка, например "filename".
===

**Comment by DItPromoil** [comment]
Дак в том то и дело, если б подключение к Астериску шло напрямую, я б прописал данные строчки в этот файл. Но у меня подключение идет через файл cdr_odbc.conf. Где данный синтаксис не работает

**Comment by prog-it** [comment]
Используйте подключение через cdr_adaptive_odbc. 
cdr_odbc умеет работать только со стандартными полями, т.е. не может использовать алиасы. В cdr_adaptive_odbc.conf можно будет прописать алиасы, которые нам нужны. Вот [тут](http://forum.asterisk.ru/viewtopic.php?f=3&t=3919) еще можно почитать.
Если получится, отпишитесь.

**Comment by DItPromoil** [comment]
Спасибо )
Я вышел из ситуации немного иным способом. Я не стал добавлять никаких новых полей в таблицу. А просто использовал поле табличное поле uniqueid. т.к. оно уже записывается, и все записи там индивидуальны, ну просто не может быть что два человека вплоть до милисекунды начали звонить. Соответственно выбрав данное поле я избавился от двух ненужных столбцов в таблице. Файл записи разговора  создается как раз используя только UNIQUEID. 
Затем поправил немного php скрипты, где этого требовалось, и вуалая - записи прослушиваются. Только столкнулся с проблемой - ваш плеер не хочет проигрывать записи, он просто на них зависает, по этому я сделал проигрывание через стандартный плеер. <audio controls src="records/monitor/'.$recorded_file.'" type=\"audio\" ></audio>

Остается только настроить правильно диалплан, чтоб можно было записывать внешние, как входящие так и исходящие, звонки только у определенных номеров

**Comment by prog-it** [comment]
У вас в каком формате хранятся записи звонков ? Плеер не воспроизводит WAV.
У меня используется MP3)

**Comment by DItPromoil** [comment]
Упс... как раз таки WAV. Совсем про это забыл.
