### ISSUE TITLE
Заменить app_macro на app_stack

### ISSUE THREAD

**Issue by mammuthus** [prog-it/Asterisk-CDR-Viewer-Mod#132]
Необходимо заменить использованное в коде обращение к модулю `app_macro`, т.к. он [устарел ](https://wiki.asterisk.org/wiki/display/AST/app_macro+Deprecation)и отсутствует в стандартной поставке последних версий. Вместо него нужно использовать модуль `app_stack`.

Обращение к отсутствующему модулю вызывает ошибку
`pbx.c:2907 pbx_extension_helper: No application 'Macro' for extension (context,,)`

Проверить отсутствие устаревшего модуля можно через `module show like macro` 
(верный вывод: `0 modules loaded`)

**Comment by sardigital** [comment]
не вижу проблемы собирать пакеты с нужными модулями

**Comment by sardigital** [comment]
но нужны подробности как использовать app_stack и в чем различия от app_macro

**Comment by mammuthus** [comment]
> не вижу проблемы собирать пакеты с нужными модулями

Если честно, не вижу смысла спорить о том, стоит или не стоит использовать deprecated модули, кмк, ответ очевиден. Тем более, что `app_macro `был объявлен deprecated уже много лет назад и существовал в дефолт билде только из-за обратной совместимости. И, наконец, его оттуда выпилили :)

`app_stack `плохо документирован, я остановился на `GoSub`. Отличие от `app_macro` будет только в передаче дополнительных параметров (экстеншена и приоритета):

Вместо
`exten => _X.,1,Macro(rec,${CALLERID(num)},${EXTEN})`
Использовать
`exten => _X.,1,GoSub(rec,s,1(${CALLERID(num)},${EXTEN}))`

Сделаю PR как закончу с настройкой, тикет закрываю.
