### ISSUE TITLE
Комментарии

### ISSUE THREAD

**Issue by Isik-Sergey** [prog-it/Asterisk-CDR-Viewer-Mod#138]
При добавлении комментария галка загорается красным цветом и ничего не происходит. Но, если вручную в базе в поле userfield добавить текст, он отображается в соответствующем поле комментарий. Похоже проблема при добавлении текста в базу, как дебажить?

**Comment by Isik-Sergey** [comment]
Шо, никто не подскажет :-(

**Comment by ametjan** [comment]
Похоже проект не работает, сейчас сами исправляем.

**Comment by kerstvo** [comment]
в таблице `cdr` должна быть колнка `id` с автоинкрементом (или просто уникальным ключом)

**Comment by Isik-Sergey** [comment]
Огроменное спасибо вам, все получилось. ЗАРАБОТАЛОО!!!
