### ISSUE TITLE
Подскажите почему не получается прикрутить авторизацию?

### ISSUE THREAD

**Issue by leksnsk** [prog-it/Asterisk-CDR-Viewer-Mod#14]
Добрый день.
По инструкции в Readme  надо сделать так:
htpasswd -c /path/to/.htpasswd admin
Location "/path/to/script"
    AuthName "Asterisk"
    AuthType Basic
    AuthUserFile /path/to/.htpasswd
    AuthGroupFile /dev/null
    require valid-user
/Location

htpasswd создал.
htpasswd -c /var/www/html/Asterisk/.htpasswd admin

Создал в /etc/apache2/conf-enabled/aster.conf  с содержимым:

Location "/var/www/html/Asterisk/index.php"
    AuthName "Asterisk"
    AuthType Basic
    AuthUserFile /var/www/html/Asterisk/.htpasswd
    AuthGroupFile /dev/null
    require valid-user
/Location
И захожу без авторизации.
Что я делаю не так?

**Comment by prog-it** [comment]
У меня нет возможности проверить, т.к. используется *nginx*. С nginx проверял, все работает. Должно работать и с Apache, скрипт здесь не при чем.
При создании .htpasswd надеюсь указали пароль... Попробуйте вместо добавления в конфиг Апача, создать файл .htaccess в папке со скриптом. Примерно такого вида:
***
AuthName "Asterisk"
AuthType Basic
AuthUserFile /path/to/.htpasswd
AuthGroupFile /dev/null
require valid-user
***
А также необходимо отредактировать в скрипте $admin_user_names.

**Comment by dyuk72** [comment]
А  в скрипте $admin_user_names что именно редактируется? 
"admin"? Простите за наивный вопрос, новичок пока, разбираюсь только и тоже очень надо "прикрутить" авторизацию

**Comment by dyuk72** [comment]
А понял: $admin_user_names - 'admin'. Так? Это в файле config.inc.php
А в .htpasswd эту строку надо прописать?

**Comment by prog-it** [comment]
Да, все так.
