### ISSUE TITLE
Запрет на удаление записей разговора

### ISSUE THREAD

**Issue by RSA00** [prog-it/Asterisk-CDR-Viewer-Mod#148]
Как можно запретить из меню определенным пользователям удалять записи разговоров ?

**Comment by greemag** [comment]
Для этого потребуется доработка системы, разграничение прав не предусмотренно в настоящий момент.

**Comment by RSA00** [comment]
хорошо, а в текущем варианте запретить удаление всем ?

**Comment by greemag** [comment]
Да, изучи inc/config/config.php там подробно описаны настройки с русскими комментариями

**Comment by RSA00** [comment]
Вопрос снят, не заметил описание. спасибо
