### ISSUE TITLE
Формат хранения записей звонков по папкам

### ISSUE THREAD

**Issue by mttzzz** [prog-it/Asterisk-CDR-Viewer-Mod#15]
Добрый день, версия 2.2.4
Раскладываю звонки по папкам 2015/12/14 астериском, выбираю формат 4 в конфиг файле. Не видны звонки. Если же звонки в одной папке и выбран формат 0, то всё нормально. подскажите куда копать

**Comment by mttzzz** [comment]
отбой разобрался. В конфиг файле указал цифру 4 без кавычек.

**Comment by mttzzz** [comment]
А нужно было с кавычками - '4'

**Comment by prog-it** [comment]
Вообще нужно именно 4, стоит проверка на соответствие типа. Т.е.
`$system_storage_format = 4;`

Если сделать как вы, т.е. с ковычками, то выполняется это условие 
`Если др. значение, то все записи хранятся в одной папке (/var/calls)`

Проверьте, у вас действительно все работает с ковычками, может быть вы копировали файлы для проверки в одну папку и поэтому показывает записи звонков.

**Comment by prog-it** [comment]
У вас Asterisk сам распределяет по папкам или используется скрипт для распределения ?
Если используется скрипт, то вам нужен формат: 2

**Comment by mttzzz** [comment]
астериск сам по папка распределяет. Странно что вы говорите что кавычки не нужны.
Все остальные параметры заданы именно в кавычках. Сейчас проверю, возможно я рано обрадовался

**Comment by mttzzz** [comment]
да, именно так, рано я обрадовался.

**Comment by mttzzz** [comment]
Ну как же так, структура есть /2015/12/14, файлы там есть, почему он их не видит.

Т.е. у меня сейчас лежат файлы и просто в /var/blablala/calrecords и в /var/blablala/calrecords/2015/12/14. Файлы одинаковые, ставлю 0 - видит файлы, ставлю 4, - не видит файлы

**Comment by prog-it** [comment]
возможно что-то с правами на файлы/папки

**Comment by mttzzz** [comment]
поставил права 0777 и действительно всё заработало. Но зачем ему такие права? с 0774 не видит файлов. Ему же их только читать, зачем ему права 0777?

**Comment by prog-it** [comment]
Нужно правильно поставить владельца и группу. Скорее всего это www-data

**Comment by mttzzz** [comment]
группа и владелец у меня asterisk, он же создает файлы и папки. Придется в диалплане. И он создает файл с правами 0664, это взято из вашего скрипта. При этом с этими же правами фалы прекрасно видит ваша панель детализации, когда они лежат в одной папке, но как только выбираешь стораж формат 4 и файлы в разных папках, то он их не видит, чудеса. Какие права необходимы чтобы оно работало?

**Comment by mttzzz** [comment]
нужны права хотя бы 755, тогда файлы видны, поставил это в скрипт, у вас стоит chmod o+r и с таким вариантом не работает, а вот chmod 755 работает

**Comment by mttzzz** [comment]
Победил вот такой конструкцией
exten => s,n,Set(monopt=nice -n 19 /usr/bin/lame -b 32  --silent "${DIR_RECORDS}${fname}.wav"  "${DIR_RECORDS}${fname}.mp3" && rm -f "${DIR_RECORDS}${fname}.wav" && chmod 755 "${DIR_RECORDS}${fname}.mp3");
exten => s,n,Set(monopt2=chmod 755 chmod 755 `find /var/www/html/callrecords/ -type d`);

Теперь и каталог и файл имеет 755 и панель видит такие файлы

**Comment by mttzzz** [comment]
ну и тут ессно: exten => s,n,MixMonitor(${DIR_RECORDS}${fname}.wav,b,${monopt} && ${monopt2});
