### ISSUE TITLE
Проигрыватель WAV-файлов

### ISSUE THREAD

**Issue by Korgoth1234** [prog-it/Asterisk-CDR-Viewer-Mod#16]
Добрый день,

Есть ли возможность прикрутить проигрыватель WAV-файлов? 
Например этот - https://github.com/datacompboy/WavPlayer
Или вообще встроенный в браузер. Писать в mp3 астериском требует слишком много ресурсов, да и WAV занимают гораздо меньше места.

К сожалению своих знаний нехватает чтобы поправить php :(

Заранее благодарен.

**Comment by prog-it** [comment]
Встроенный в браузер не стал делать, т.к. работает не во всех браузерах. Посмотрю на днях, что можно еще сделать.

**Comment by Glip** [comment]
День добрый. Не появилось идей, что можно сделать?

**Comment by prog-it** [comment]
В ближайшем обновлении постараюсь решить эту проблему.

**Comment by prog-it** [comment]
HTML5 плеер воспроизводит WAV файлы.
