### ISSUE TITLE
Пара вопросов

### ISSUE THREAD

**Issue by ASTIN-UA** [prog-it/Asterisk-CDR-Viewer-Mod#19]
Здравствуйте. Пару дней назад наткнулся на вашу разработку. Все просто круто! Но, как всегда есть но. Нет возможности конвертировать все в mp3. Есть ли какая то возможность воспроизводить родные wav файлы? И еще, в стандартном cdr FreePbx можно при поиске по входящему номеру писать несколько номеров через запятую. Можно ли реализовать это и в вашей версии? Иногда нужно искать сразу по нескольким номерам. Заранее спасибо!

**Comment by prog-it** [comment]
На счет воспроизведения WAV, постараюсь в ближайшем обновлении избавиться от флеш плеера и заодно решить эту проблему.
На счет поиска по нескольким номерам, посмотрю, что можно сделать. У меня, лично, такой необходимости еще не было.

**Comment by ASTIN-UA** [comment]
Могу вам отправить готовое решение на html5 плеере. У меня оно уже
работает.

9 февр. 2017 г. 15:39 пользователь "prog-it" <notifications@github.com>
написал:

**Comment by prog-it** [comment]
Какой у вас используется HTML5 плеер, какие форматы может воспроизвести ? Пока смотрю в сторону uppod html5.
Если бы отправили, было бы неплохо :)

**Comment by prog-it** [comment]
Спасибо, но, наверное, уже нет необходимости. Флеш заменен на HTML5, скоро будет выложена новая версия.
