### ISSUE TITLE
Ошибка mysql

### ISSUE THREAD

**Issue by syjet** [prog-it/Asterisk-CDR-Viewer-Mod#20]
При выборе доп. опции Параллельные звонки выдается ошибка:
PDO::errorInfo(): Array ( [0] => 42000 [1] => 1064 [2] => You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') ORDER BY unix_timestamp(calldate) ASC LIMIT 100' at line 1 )
Версия сервера: 5.5.47-0+deb8u1 - (Debian)
Веб-сервер nginx/1.6.2
Версия клиента базы данных: libmysql - 5.5.47
PHP расширение: mysqli 

Дамп прилагаю
[localhost.sql.zip](https://github.com/prog-it/Asterisk-CDR-Viewer-Mod/files/160591/localhost.sql.zip)

**Comment by syjet** [comment]
Так же не работают настройки (всегда все фильтры отображаются, независимо от настроек)
### Включение / Отключение показа условий поиска и типов отчетов
## Если 1 - показать, 0 - скрыть
$display_search = array();
# Показ типа отчета - Параллельные звонки
$display_search['chart_cc']=0;
# Показ типа отчета - ASR и ACD (Коэффициент отвеченных вызовов / Средняя продолжительность вызова)
$display_search['asr_report'] = 0;
# Показ условия поиска - Входящий канал
$display_search['channel'] = 0;
# Показ условия поиска - Имя звонящего
$display_search['clid'] = 0;
# Показ условия поиска - DID (Внешний номер)
$display_search['did'] = 0;
# Показ условия поиска - Исходящий канал
$display_search['dstchannel'] = 0;
# Показ условия поиска - Код аккаунта
$display_search['accountcode'] = 0;
# Показ условия поиска - Описание (userfield)
$display_search['userfield'] = 0;
# Показ условия поиска - Приложение
$display_search['lastapp'] = 0;

**Comment by orynkanov** [comment]
Для отображения параллельных звонков:
Строка 614:
if ( strlen($where) > 9 ) {

Изменить на
if ( strlen(trim($where)) > 1 ) {

На строке 613 переменная $where состоит из пробелов, если не заданы условия и sql запрос неправильный получается.

**Comment by varnav** [comment]
Помогло. Автор, поправь плиз в исходниках.

**Comment by prog-it** [comment]
Будет исправлено в ближайшем обновлении.
