### ISSUE TITLE
uft8 кодировка

### ISSUE THREAD

**Issue by mttzzz** [prog-it/Asterisk-CDR-Viewer-Mod#21]
В астериске в настройках mysql поставил отравлять записи в cdr в utf8, теперь все записи в самой базе отображаются корректно, раньше были кракозябры в базе, но нормально выводилось в Asterisk-CDR-Viewer-Mod, теперь всё правильно выводится в базе, но вопросы вместо символов в Asterisk-CDR-Viewer-Mod. В браузере стоит utf8. Как пофиксить?

**Comment by prog-it** [comment]
У вас базе используется не правильная кодировка. Сделайте для всех полей типа `VARCHAR` кодировку **utf8_general_ci** и все будет нормально отображаться.
