### ISSUE TITLE
не виден файл записи разговора

### ISSUE THREAD

**Issue by alexy2601** [prog-it/Asterisk-CDR-Viewer-Mod#29]
Добрый вечер, 
elastix 2.5.0 (asterisk 11.17.1)
в отчете Asterisk-CDR-Viewer-Mod не вижу файлов с записями разговоров, в статусе answered. В строке файл - перечеркнутый серый круг. Звонки 'не отвечено' и 'занято' можно прослушать и скачать.
При этом сам файл записи существует и лежит в /mnt/zapis/2016/09/22, uid файла и данные в отчете совпадают.
Переменная $sysytem_monitor_dir = '/mnt/zapis';
$system_storage_format = 4;
Можно ли как-то включить дебаг и посмотреть   

Выборка из cdr

| 2016-09-22 21:53:49 | 404  | 404 | 89043042877 | from-internal | SIP/404-00006168 | SIP/dr2203121-00006169 | Dial    | SIP/dr2203121/89043042877,300, |       18 |      11 | ANSWERED    |        3 |             | 1474563229.24936 |           | /mnt/zapis/2016/09/22/out-89043042877-404-20160922-215349-1474563229.24936.wav                  | 404  | 404  | 73512203121   |               |          |

**Comment by Pazzzlik** [comment]
![2016-09-27_123007](https://cloud.githubusercontent.com/assets/15156996/18867779/3ebd8e14-84ae-11e6-9f09-19861efc5811.png)

**Comment by Pazzzlik** [comment]
А записи в wav?

**Comment by alexy2601** [comment]
Немного разобрались. Записи успешных разговоров успешно конвертятся в mp3 после того как положили трубку, но в cdr в поле recordingfile записываются с префиксом /mnt/zapis/ и с разрешением wav.  
В итоге в скрипте конвертирования файла и апдейта полей с файлом записи, просто изменили условие на "WHERE recordingfile like "%'$file'.wav""
Сейчас все норм, файлы видятся и проигрываются, спасибо за разработку.
