### ISSUE TITLE
Не верный период "текущая неделя"

### ISSUE THREAD

**Issue by SergeyDjam** [prog-it/Asterisk-CDR-Viewer-Mod#31]
При выборе периода "текущая неделя" в 2.2.5 выставляется период на месяц вперед. 

К примеру сегодня 29.11 при выборе периода "текущая неделя" устанавливается с 28.12.2016 по 04.12.2016

**Comment by prog-it** [comment]
Это происходит только в конце месяца. Постараюсь это исправить в ближайшем обновлении.

**Comment by prog-it** [comment]
Исправлено в версии 2.6.4
