### ISSUE TITLE
Как добавить триггер без вкладки триггер в phpmyadmin

### ISSUE THREAD

**Issue by Dreyti** [prog-it/Asterisk-CDR-Viewer-Mod#34]
Здравствуйте! Очень нужен ответ на вопрос в заголовке. 

PhpMyAdmin древний. Вкладки триггеры нет. Права на создание триггеров имеются.
Через SQL пробовал добавлять по мануалам, но постоянно пишет что синтаксис неверный. Явно где-то косячу.

Apache/2.2.22 
Версия MySQL-клиента: 5.5.53
Phpmyadmin 3.4.10.1deb1

`BEGIN
	IF ((NEW.dst = 's' OR NEW.dst = '~~s~~') AND NEW.realdst != '') THEN 
		SET NEW.dst = NEW.realdst;
	END IF;
END`

**Comment by Dreyti** [comment]
Делал так и еще в каких то вариациях. Может у кого есть какие идеи на этот счет?

`delimiter //
CREATE TRIGGER before_realdst BEFORE INSERT ON realdst
BEGIN
	IF ((NEW.dst = 's' OR NEW.dst = '~~s~~') AND NEW.realdst != '') THEN 
		SET NEW.dst = NEW.realdst;
	END IF;
END
//
delimiter ;`

**Comment by sardigital** [comment]
Adminer

**Comment by Dreyti** [comment]
Спасибо за совет! Админер шикарная штука. Триггер добавил, но проблема которую он должен был исправить так и осталась....

**Comment by Dreyti** [comment]
Вопрос решился добавлением в диалплан exten => h,1,Set(CDR(realdst)=${DIALEDPEERNUMBER})
После команды Dial. Может кому пригодится.
