### ISSUE TITLE
Не показываются записи звонков за прошлые дни

### ISSUE THREAD

**Issue by Dreyti** [prog-it/Asterisk-CDR-Viewer-Mod#35]
Ситуация следующая. Есть VPS сервер c астериском. Звонки пишутся на Яндекс.Диск (Диск примонтирован в  /mnt/backup. Все работало замечательно пока хостер не провел плановую замену оборудования. Конфиги все те что и были раньше. Все пишется, крутится но звонки в CDR доступны только за текущий день. 
Кто-то сталкивался? В какую сторону смотреть?

$system_storage_format = 2;
Записи переносятся скриптом по подпапкам раз в стуки.

**Comment by sardigital** [comment]
скрипт для перемещения записей в студию :)

**Comment by Dreyti** [comment]
Привет! Проблема решилась в тот же день. Оказалось что webdav заглючил и не подключал подпапки. Решилось перезапуском сервиса.
