### ISSUE TITLE
Добавить фильтрацию номеров в статистику

### ISSUE THREAD

**Issue by Dreyti** [prog-it/Asterisk-CDR-Viewer-Mod#36]
Приветствую всех!
Назрел такой вопрос. Нужно сделать фильтрацию номеров в статистике таким образом чтобы входящие внешние номера и исходящие на внешние номера не повторялись.

т.е. если номер 111 звонил на номер +7 000 0000 0000 - 3 раза нужно вывести его один раз (+7 000 0000 0000) и наоборот если номер   +7 000 0000 0000 звонил на любой входящий больше одного раза отобразить его один раз (+7 000 0000 0000).

Вся эта ерунда нужна чтобы собиралась статистика без дубляжа номеров (бред выданный маркетологом). 

Если кто-то сталкивался с таким извращением просьба натолкнуть куда копать. А то пока приходит в голову только бред сивой кобылы и маты в сторону того кто эту ерунду придумал. 

Как я вижу это все: Добавить чекбокс в котором прописано условие выводить только один номер, но что делать с операторами? Ведь принять или перезвонить клиенту могут разные операторы по одному и тому же вопросу...?

Ps.: Сервер VPS ubuntu 12.04, Asterisk 13, Астер патчился на предмет дубляжа входящих звонков когда при входящем в статистику выводился ответивший на звонок оператор и все не ответившие.

**Comment by Dreyti** [comment]
P.S.: Вариант через Call Graph и группировку по типу звонка не предлагать я про него знаю, а упырю маркетологу этот вариант не подходит.

**Comment by Dreyti** [comment]
В качестве временного решения добавил доп.пункт "Статистика обращений" в параметры "Дополнительные опции".
Скопировал секцию "График звонков" и чуть-чуть подправил под желания "маркетолога", а именно:
1. Добавил нумерацию строк с телефонами
2. Вывел подсчет элементов массива в шапке и футере
3. Вывел общее время звонка с момента поднятия трубки
4. Вывел все записи разговоров для этого номера независимо от того с каким оператором общался позвонивший. 

Решение некрасивое, но лучше ничего не придумал.

**Comment by prog-it** [comment]
С таким дело иметь не приходилось :).
