### ISSUE TITLE
Обрыв воспроизведения записи

### ISSUE THREAD

**Issue by Pazzzlik** [prog-it/Asterisk-CDR-Viewer-Mod#38]
Релиз 2.3.2

После 5 секунд прослушивания файла в браузере Google Chrome (Версия 56.0.2924.87) воспроизведение прерывается с надписью "Файл не найден". В Mozilla Firefox все корректно. 

![2017-02-13_095937](https://cloud.githubusercontent.com/assets/15156996/22873777/3b21e07e-f1d3-11e6-9fa1-9186b5d9311c.png)

**Comment by prog-it** [comment]
Действительно в Chrome есть такое и **только на коротких записях при длительности менее около 75 секунд**. Попробуйте на длинных записях как работает в Chrome.
Скорее всего дело в HTML5 плеере, поищу альтернативу.

**Comment by prog-it** [comment]
Все из-за отдачи файла записи скриптом, будут исправлено в ближайшем обновлении

**Comment by prog-it** [comment]
Исправлено. Отпишитесь, если все работает

**Comment by Pazzzlik** [comment]
Да, все работает. Спасибо!

**Comment by NiGGaZJr** [comment]
Всем привет! Такая же проблема, но при этом файл записан в правильном формате wav.
Отображает "Файл не найден", во всех браузерах.
В консоли есть ошибки:
GET http://10.122.240.33/cdr/dl.php?f=MTUxMTUwMTU0MC4zLTIwMTctMTEtMjQtMTFfMzItMjIzLTIwMC53YXY= 404 (Not Found)
Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause(). https://goo.gl/LdLk22

**Comment by NiGGaZJr** [comment]
Нашел в чем была проблема (в логе Apache):
PHP Warning:  finfo_file(/var/calls/1511502576.6-2017-11-24-11_49-87475975431-3312570.wav): failed to open stream и т.д.
Выставил группу "nogroup [65534]" на папку /var/calls/ и воспроизведение заработало
