### ISSUE TITLE
Ошибка в макросе для extensions.conf

### ISSUE THREAD

**Issue by nsdonner** [prog-it/Asterisk-CDR-Viewer-Mod#4]
День добрый, в Readme у вас ошибка в макросе для старого диалплана, в строчке

exten => s,n,Set(CDR(realdst)=${called});

вместо названия переменной ${called} должно быть ${ARG2} т.к. в старом синтаксисе в макросе не описываются имена переменных, а просто идут по счету ARG1 ARG2 и т.д.

**Comment by prog-it** [comment]
Спасибо. Будет исправлено в завтрашнем обновлении.

**Comment by prog-it** [comment]
Обновлено.
