### ISSUE TITLE
подключение к sqlite

### ISSUE THREAD

**Issue by dmitrii507** [prog-it/Asterisk-CDR-Viewer-Mod#41]
Есть ли возможность настройки подключения, к sqlite вместо подключения к mysql

**Comment by prog-it** [comment]
Да, есть (sqlite, sqlite3...). Поддерживаются все базы, с которыми работает PDO драйвер.

**Comment by dmitrii507** [comment]
Отлично, а как настроить подключение к ней？

**Comment by prog-it** [comment]
Сам sqlite не пробовал, но должно работать.
Нужно будет изменить в файле `index.php` строчку:
`$dbh = new PDO("$db_type:host=$db_host;port=$db_port;dbname=$db_name", $db_user, $db_pass, $db_options);` примерно на это `$dbh = new PDO('sqlite:my/database/path/database.db');`. Здесь указан примерный путь к файлу с sqlite, тогда параметры `$db_*` в конфиге можно уже не изменять.

Отпишитесь, если будет работать, добавлю для sqlite параметры подключения более красивым образом.

**Comment by dmitrii507** [comment]
Заменил строку при клике на найти пишет
PDO::errorInfo(): Array ( [0] => HY000 [1] => 26 [2] => file is encrypted or is not a database )

**Comment by prog-it** [comment]
Что-то с несоответствием версии sqlite и PHP. Посмотрите в Google по описанию ошибки. Можно посмотреть для начала здесь: [здесь](http://stackoverflow.com/questions/1513849/error-file-is-encrypted-or-is-not-a-database) и [здесь](http://sqlite.1065341.n5.nabble.com/Getting-error-quot-file-is-encrypted-or-is-not-a-database-quot-when-trying-simple-C-example-td75837.html)

У себя не могу проверить, т.к. использую MySQL. Возможно базу нужно переконвертировать в другой формат, например sqlite3.

**Comment by vasvlad** [comment]
Для успешного испльзования sqlite3 необходимо также поправить вот эту строку
                      $query = "SELECT *, unix_timestamp(calldate) as call_timestamp FROM $db_table_name $where $order $sort LIMIT $result_limit";
на вот такую:
                        $query = "SELECT *, strftime('%s', calldate) as call_timestamp FROM $db_table_name $where $order $sort LIMIT $result_limit";
И есть проблемы с триггером.
