### ISSUE TITLE
Возможность удалять записи разговоров.

### ISSUE THREAD

**Issue by Tipuxa** [prog-it/Asterisk-CDR-Viewer-Mod#42]
Здравствуйте.

Будет ли добавлен данный функционал? 

Спасибо.

**Comment by prog-it** [comment]
Добавить можно, но тогда это сможет сделать любой пользователь. В скрипте нет как такового разграничения прав.

Вас интересует возможность удаления конкретной записи ? т.е. чтобы рядом с кнопками прослушать/скачать запись была еще одна "Удалить"

**Comment by Tipuxa** [comment]
Да, именно так.

**Comment by prog-it** [comment]
Скоро будет добавлено.

**Comment by prog-it** [comment]
Пробуйте.

**Comment by Tipuxa** [comment]
Работает.

Спасибо!

**Comment by Dreyti** [comment]
Приветствую!
> В скрипте нет как такового разграничения прав.
Планируете реализовать? Очень интересно было бы взглянуть. Над этой проблемой бился еще в старом скрипте. 

У себя реализовал через сессии, пользователь должен быть админом с активной сессией тогда можно удалить запись в бд (Все руки не доходят сделать чтобы на месте удаленной записи выводился каммент "Запись удалена %user% причина: %reason%".) Остальные могут только смотреть если залогинены как юзеры. Правда базу пришлось серьезно видоизменить да и от изначального вьювера осталось не так уж много.

**Comment by prog-it** [comment]
Наверное, что-то добавлю в этом направлении в ближайшее время, чтобы не пришлось видоизменять базу. Сначала необходимо продумать логику, например, как быть с использованием нескольких конфигов при таком подходе.

**Comment by gn-pvl** [comment]
Можете сделать так, чтобы при удалении записи с вебморды, в БД очищалось поле "filename"?
Сейчас если удалить запись, то в БД остаётся имя файла.

**Comment by prog-it** [comment]
Будет добавлено в ближайшие дни.

**Comment by prog-it** [comment]
> Можете сделать так, чтобы при удалении записи с вебморды, в БД очищалось соответствующее поле "filename"?
> Сейчас если удалить запись, то в БД остаётся имя файла.

Добавлено в версии 2.6.1
