### ISSUE TITLE
Автоматическое удаление старых записей разговоров

### ISSUE THREAD

**Issue by bestann** [prog-it/Asterisk-CDR-Viewer-Mod#44]
Не нашла у вас в Readme, есть ли такая возможность. Насколько я знаю, скрипт в Интернете есть. Удобно было бы настраивать удаление по времени хранения: например храним 60мес (через веб задавать сколько храним), все более старые удаляем (по истечении 60 мес файлы удаляются каждый день по 1 дню). Также учитывать фактор оставшегося места на диске: если места осталось меньше 500 Мб (размер определяем), удаляем часть файлов (например за 1 день).

**Comment by prog-it** [comment]
Asterisk CDR Viewer Mod только для получения отчетов. Чтобы что-то хранить, нужно уже создавать доп. таблицы в базе. 
Для удаления старых записей можно написать доп. bash скрипт. Можно добавить данную возможность в скрипт **proc_records.sh** (папка docs) и запускать его по CRON.
В скрипте зададите количество дней, после которых файлы будут удалены, так будет удобно ?

**Comment by bestann** [comment]
Да.

**Comment by prog-it** [comment]
Добавлено удаление старых записей
