### ISSUE TITLE
short open tag

### ISSUE THREAD

**Issue by and-rey** [prog-it/Asterisk-CDR-Viewer-Mod#47]
В коде иногда используется <?  ?>. не у всех включен short open tag. Мелочь, но пришлось просмотреть код чтобы понять почему не работает отключение условий выборки из конфига.
И еще поправил у себя условие в func.inc.php в функции formatFiles в коментах Аудио, Архив, Факс
c `filesize($rec['path'])/1024 >= $system_fsize_exists........`
на `$row['disposition'] == 'ANSWERED'`
может не разобрался во всей логике, но в данном случае не режутся короткие разговоры

**Comment by prog-it** [comment]
Шорт-теги будут исправлены в ближайшем обновлении.

Что касается функции formatFiles, то смотрите внимательно комментарии в конфиге и значение переменной: `$system_fsize_exists`. Задайте значение 0, чтобы появились короткие записи разговоров, т.е. ваши правки лишние.

**Comment by prog-it** [comment]
Какая у вас версия PHP. если не секрет. В PHP 5.4 и выше шорт-теги включены по умолчанию, а также эта информация поможет для нового релиза.

**Comment by and-rey** [comment]
Понял, спасибо. PHP 5.3.3
