### ISSUE TITLE
Поиск нецифровых номеров

### ISSUE THREAD

**Issue by Olpag** [prog-it/Asterisk-CDR-Viewer-Mod#48]
Здравствуйте.
Можно ли реализовать поиск нецифровых номеров? У меня есть такие DID.

![did_alpha](https://cloud.githubusercontent.com/assets/20798477/26308957/fc404624-3f03-11e7-95ca-a772c0036f6b.jpg)
![did_alpha2](https://cloud.githubusercontent.com/assets/20798477/26308956/fc1bdffa-3f03-11e7-838e-9725f1b65724.jpg)

**Comment by prog-it** [comment]
Только у себя проверил, все работает. 
Скорее всего, вы ввели в поле поиска "Куда звонили" значение с пробелом, пробелы в начале и конце не обрезаются. А также может быть ввели без пробелом, а в базе значение с пробелом. Попробуйте еще раз.

**Comment by Olpag** [comment]
Да, в поле DID поиск работает 👍 )
Я же говорю о поле "Куда звонили". Условие поиска DID выключено, как на картинке.

**Comment by Olpag** [comment]
если не ошибаюсь, то значение "Куда звонили" ищется в БД по полю "dst", а отjбражает значение поля DID

**Comment by prog-it** [comment]
У себя проверил именно поле "Куда звонили", все работает. Добавил в базу значения с вашего скрина.
У вас в базе в поле "dst" значение "euroclient" ?
В базе производится поиск по полю "dst", и выводятся значения из базы тоже по полю "dst".
![screen_20170522_1837_001](https://cloud.githubusercontent.com/assets/12819338/26311452/cb049b0e-3f1d-11e7-813b-51d0b70ff834.jpg)

**Comment by Olpag** [comment]
У меня в базе "dst" значение "600", "dcontext" - "ext-group", "DID" - "euroclient"

**Comment by prog-it** [comment]
Так вам нужно вводить значение для поиска в поле "DID (если есть)" или в поле "Куда звонили" значение 600. Вводите в поле "DID (если есть)", ищет в базе в "did", вводите в поле "Куда звонили", ищет в базе в "dst"

**Comment by Olpag** [comment]
Согласен. Есть один нюанс. Из полей поиска у клиента только "Кто звонил" и "Куда звонили". И в колонке "Куда звонили" отображается DID, не "dst". Ну и, естесственно,  он пытается искать по полю "Куда звонили", вводя DID (то, что он видит), то ничего не находит.

**Comment by prog-it** [comment]
Да, если поле did в базе не пустое, то в "Куда звонили" выведет именно did, а не dst. 
Посмотрим, что можно сделать. Добавить еще одну колонку для DID с возможностью скрытия в конфиге, а вместо "Куда звонили" выводить dst всегд. Так будет удобно ?

**Comment by Olpag** [comment]
Да, было бы неплохо.  
И сразу еще две просьбы. 
1. Можно ли реализовать отбражение (и поиск) полного ID канала:
SIP/1000-00000025, а не SIP/1000
Local/1000@from-internal-00000000;1 , а не Local/1000@from-internal
Иногда очень не хватает. Может реализовать это опцией в config.inc.php

2.  Возможность отключать колонку "Описание", зачастую она не нужна.
$display_column['userfield'] = 0;
Я у себя добавил эту возможность

**Comment by prog-it** [comment]
1. Если сделать отображение "SIP/1000-00000025" во всплывающей подсказке, будет удобно ?
Поиск по полному каналу и так работает, только проверил.
2. Будет добавлено в новом релизе. Также в новом релизе будет возможность Изменять через веб-интерфейс поле "Описание" с сохранением в базе.

**Comment by Olpag** [comment]
1. Не совсем удобно, из всплывающей подсказки копипаст не получается, а ручками набирать кучу разных символов долго и  легко ошибиться ))). 
А поиск по полному каналу действительно работает, отлично!

**Comment by prog-it** [comment]
Будет добавлено. Возможно, с копированием в буфер при нажатии (через JS)

**Comment by Olpag** [comment]
Спасибо! Отличный вьювер.

**Comment by Olpag** [comment]
Спасибо, все работает.
