### ISSUE TITLE
Не проигрываются файлы звонков и не скачиваются (mp3)

### ISSUE THREAD

**Issue by IvanTen** [prog-it/Asterisk-CDR-Viewer-Mod#5]
Добрый день,
Подскажите пожалуйста, не проигрываюся файлы,
пути:
http://192.168.0.2/dl.php?f=MTQ0MzUyMzY3NS44NS0yMDE1LTA5LTI5LTEzXzQ3LTEwMDEtMTAwMi5tcDM=
http://192.168.0.2/dl.php?f=MTQ0MzUyMjg1Ny44Mi0yMDE1LTA5LTI5LTEzXzM0LTEwMDEtNzQ5NTM2ODg0OTAubXAz
http://192.168.0.2/dl.php?f=MTQ0MzUyMjYwMy43My0yMDE1LTA5LTI5LTEzXzMwLTEwMDEtMTAwMi5tcDM=
http://192.168.0.2/dl.php?f=MTQ0MzUyMjMyNy42Ny0yMDE1LTA5LTI5LTEzXzI1LTEwMDEtMTAwMi5tcDM=
на сервере файлы mp3 в /var/calls

в конфиге значение не 1.

Где можно эти пути поправить?

Спасибо

**Comment by IvanTen** [comment]
Сам разобрался:

В файле dl.php нужно строку дописать:

******************************* исходный ********************************************

<?php

require_once 'inc/config.inc.php';
require_once 'inc/sendfile.class.php';

use SendFile\sendFile as sendFile;

if (isset($_REQUEST['f'])) {
	$fname = base64_decode($_REQUEST['f']);
	$file = $system_monitor_dir . '/' . $fname;
	$send = new sendFile;
	$send->Path = $file;
	$send->send();
	exit;
}

else if (isset($_REQUEST['csv'])) {
	$fname = base64_decode($_REQUEST['csv']);
	$file = $system_tmp_dir . '/' . $fname;
	$send = new sendFile;
	$send->Path = $file;
	$send->ContentType = 'text/csv';
	$send->send();	
	exit;
}

header('HTTP/1.1 404 Not Found');
**********************************************************************************
*************************** добавил строку *********************************

<?php

require_once 'inc/config.inc.php';
require_once 'inc/sendfile.class.php';

use SendFile\sendFile as sendFile;

if (isset($_REQUEST['f'])) {
	$fname = base64_decode($_REQUEST['f']);
	$file = $system_monitor_dir . '/' . $fname;
	$send = new sendFile;
	$send->Path = $file;
        $send->ContentType = 'text/mp3';    # !!! эту строку добавил 
	$send->send();
	exit;
}

else if (isset($_REQUEST['csv'])) {
	$fname = base64_decode($_REQUEST['csv']);
	$file = $system_tmp_dir . '/' . $fname;
	$send = new sendFile;
	$send->Path = $file;
	$send->ContentType = 'text/csv';
	$send->send();	
	exit;
}

header('HTTP/1.1 404 Not Found');

************************************************************************************************

**Comment by prog-it** [comment]
Все правильно. В вашей версии PHP отсутствует класс `finfo` для авто определения типа файла, скорее всего у вас версия PHP ниже 5.3. Чтобы работало, нужно установить расширение `PECL fileinfo`.
Лучше исправьте строчку 
`$send->ContentType = 'text/mp3';`
на
`$send->ContentType = 'audio/mpeg';`

**Comment by djserg-minyar** [comment]
Добрый день, подскажите, как заставить встроенный плеер воспроизводить wav файлы?

**Comment by djserg-minyar** [comment]
Формат нужный поставил

### Формат аудио, в котором записываются записи звонков
$system_audio_format = 'wav';

**Comment by djserg-minyar** [comment]
Файлы скачиваются без проблем, видимо что то с самим плеером.

**Comment by prog-it** [comment]
Плеер *не поддерживает воспроизведение WAV*. Но воспроизводит mp3 и другие форматы. Чуть позже добавлю это в документацию.
Сделайте лучше прозрачную конвертацию в MP3, качество не страдает, но зато объем файла в несколько раз меньше! Как это сделать описано в Readme.

**Comment by djserg-minyar** [comment]
Спасибо, поправил
