### ISSUE TITLE
баг в файле /inc/load.php

### ISSUE THREAD

**Issue by sardigital** [prog-it/Asterisk-CDR-Viewer-Mod#50]
в файле /inc/load.php:

`require_once` 'inc/**S**endfile.class.php';`

при копировании через Windows имя становится строчным.

версия 2.6.0

**Comment by prog-it** [comment]
При копировании куда? Windows при копировании, например через samba, не меняет регистр имен файлов.

**Comment by sardigital** [comment]
при распаковке из zip

**Comment by sardigital** [comment]
привожу кусок load.php:

require_once 'inc/functions.php';
require_once 'inc/requests.php';
require_once 'inc/Sendfile.class.php';

В общем непонятно зачем этот класс делать с заглавной буквы

**Comment by sardigital** [comment]
баг минимальный, но при первой развертывании мешает

**Comment by sardigital** [comment]
возможно что это git for windows так себя повел

**Comment by sardigital** [comment]
можно закрывать, спасибо

**Comment by prog-it** [comment]
Имена файлов с классами положено писать с заглавной буквы, хотя и не обязательно. Скорее всего, виноват git for windows.
