### ISSUE TITLE
Неправильный выбор дат в условиях поиска

### ISSUE THREAD

**Issue by Olpag** [prog-it/Asterisk-CDR-Viewer-Mod#51]
1. При выборе шаблона "Вчера" устанавливает диапазон дат "вчера + месяц до вчерашнего дня".
2. При выборе шаблона "Предыдущая неделя" устанавливает диапазон дат "прошлая неделя + месяц до начала прошлой недели".

Для сравнения, скриншот с фильтром "Сегодня"
![today](https://cloud.githubusercontent.com/assets/20798477/26674356/e44437f2-46c8-11e7-8ff7-cc7ebc24b72f.jpg)

"Вчера"
![yesterday](https://cloud.githubusercontent.com/assets/20798477/26674375/f263223a-46c8-11e7-8165-a0a0f67c6b88.jpg)

"Предыдущая неделя"
![prev_week](https://cloud.githubusercontent.com/assets/20798477/26674386/fc76f198-46c8-11e7-80d9-86fae248e278.jpg)

**Comment by prog-it** [comment]
Да, есть такое. Пока исправить не удалось. Обычно работает неверно в начале месяца и в воскресенье. В ближайшее время выбор дат будет полностью переделан на выбор в виде календаря, тогда будет работать правильно.

**Comment by Olpag** [comment]
Ок, будем ждать.

**Comment by prog-it** [comment]
Исправлено в версии 2.6.4
