### ISSUE TITLE
Не отображаются записи в панели

### ISSUE THREAD

**Issue by max-arturo** [prog-it/Asterisk-CDR-Viewer-Mod#53]
Добрый день.
Записи сохраняются нормально, в колонке "filename" имя фиксируется.
Однако в панели записи не отображаются. Пробовал менять права на файлы/папки, менять владельца - без эффекта.

**Comment by prog-it** [comment]
Напишите полный путь к конечному файлу записи звонка, а также содержимое поля `filename` из базы для этого файла.
Файлы записей распределяются по папкам скриптом ?
Скопируйте также сюда все секцию `'system' => array(...)` из конфига, чтобы было проще понять.

**Comment by max-arturo** [comment]
Путь к файлам за сегодня: /mnt/calls/1497056442.7-2017-06-10-04_00-103-102.mp3
Содержимое графы filename: 1497056442.7-2017-06-10-04_00-103-102.mp3
Файлы распределяются по папкам скриптом.
'system' => array(
		'column_name' => 'filename',
		'tmp_dir' => '/tmp',		
		'monitor_dir' => '/mnt/calls',		
		'storage_format' => 1,
		'fsize_exists' => 1,
		'audio_format' => 'mp3',
		'audio_defconv' => 0,
		//'archive_format' => 'zip',
		'csv_delim' => ';',		
),

**Comment by prog-it** [comment]
По идее, все должно работать, настроено верно. Файлы за другие дни тоже не отображаются?
Попробуйте создать php файл в папке со скриптом и выполнить следующий код, только впишите свой путь к любому из файлов с записью звонка. Напишите, что выдаст.

```
<?php error_reporting(E_ALL | E_STRICT); ini_set('display_errors', 'On');

// Например: $path = '/mnt/calls/1497056442.7-2017-06-10-04_00-103-102.mp3';
$path = '';

if ( file_exists($path) ) {
	echo 'File exists with size: ' . filesize($path);
} else {
	echo 'File not exists';
}

```

**Comment by max-arturo** [comment]
Не отображаются ни сегодняшние записи, ни старые.
Несмотря на настройку в скрипте: "**DIR_DST="/mnt/calls/$Y/$YM/$YMD/**", записи собираются скриптом в путь "/mnt/calls/2017/2017-06-10/1497056442.7-2017-06-10-04_00-103-102.mp3".

Скрипт выдал следующее:
"Warning: file_exists(): open_basedir restriction in effect. File(/mnt/calls/1497139643.49-2017-06-11-03_07-103-102.mp3) is not within the allowed path(s): (/var/www/www-root/data:.) in /var/www/www-root/data/www/***/master/docs/test.php on line 7
File not exists"

**Comment by prog-it** [comment]
Если на сервере много пользователей, то open_basedir полностью отключать не желательно.
Прав 0755 на папки должно быть достаточно, необходимы права на "выполнение" для пользователя, от которого работает веб-сервер.
В скрипте распределения записей по папкам был баг, исправлено. Попробуйте [исправленную версию](https://github.com/prog-it/Asterisk-CDR-Viewer-Mod/blob/master/docs/proc_records.sh)

**Comment by max-arturo** [comment]
Исправленный скрипт работает как надо, спасибо!
В фильтре поиска звонков не хватает опции "искать только звонки с записями" :)
При установке прав 0776 панель не видит записи, т.е. требует исполняемого бита для всех. Сервер запускается от root'а

**Comment by prog-it** [comment]
> В фильтре поиска звонков не хватает опции "искать только звонки с записями"

В большинстве случаев для этой цели можно использовать фильтр "Статус звонка" - Отвечено, делать отдельный фильтра пока не вижу необходимости.
