### ISSUE TITLE
В столбце 'Файл ' отсутствуют значки прослушивания и удаления

### ISSUE THREAD

**Issue by triony** [prog-it/Asterisk-CDR-Viewer-Mod#54]
Приветствую.
Ubuntu 14.04.5 x64, Asterisk 11.6, ACDR-Viewer-Mod 2.6
В столбце 'Файл ' присутствует только значек на скачивание записанного файла. Возможности прослушать запись нету. Сам файл пишется нормально и его можно скачать.
Я что-то не донастроил?

**Comment by prog-it** [comment]
Скорее всего, не все настроили. Нужно больше информации.
Напишите полный путь к конечному файлу записи звонка, как он есть на диске. Если в имени файла есть номер телефона, можете заменить часть цифр на XXX.
Файлы записей распределяются по папкам скриптом ? Используется отложенная конвертация записей звонков ?
Скопируйте также сюда все секцию `'system' => array(...)` из конфига, чтобы было проще понять.

**Comment by triony** [comment]
Действительно не всё настроил:
по умолчанию 'audio_format' => 'mp3', а я пишу в wav. Поменял и всё заработало.
Прошу прощения за беспокойство.
Огромное спасибо за вьювер. Очень удобный.
