### ISSUE TITLE
Скрипт создания таблицы, ошибка в MariaDB

### ISSUE THREAD

**Issue by bestann** [prog-it/Asterisk-CDR-Viewer-Mod#55]
Не отрабатывает вот это
```
 FOR EACH ROW BEGIN
	IF ((NEW.dst = 's' OR NEW.dst = '~~s~~') AND NEW.realdst != '') THEN 
		SET NEW.dst = NEW.realdst;
	END IF;
END
```
Пишет
```
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.dst = NEW.realdst;
END IF;
```

**Comment by sardigital** [comment]
вроде в мане про триггер речь?

**Comment by bestann** [comment]
Да, про триггер. Я в бд еще не разбираюсь. Так то база создается. Второй раз ставлю.

**Comment by prog-it** [comment]
Этот скрипт создания таблицы приведен для базы данных MySQL и точно работает, для MariaDB же его скорее всего необходимо поправить. У себя нет возможности этого сделать, т.к. используется MySQL.
