### ISSUE TITLE
Не возможно скачать и прослушать за прошлые даты

### ISSUE THREAD

**Issue by olejkhar** [prog-it/Asterisk-CDR-Viewer-Mod#6]
![-1](https://cloud.githubusercontent.com/assets/15157139/10540881/de5c7120-7414-11e5-858f-78da17f3e2ba.jpg)
Привет, возможно помочь мне рушить проблему.
Не возможно скачать и прослушать запись  за прошлые даты, за текущую видит и скачивает и проигрывает, вчерашние уже нет, на след. день та же картина... файлы в каталоге есть, файлы разложены по папкам с датой.

**Comment by prog-it** [comment]
Скиньте конфиг (config.inc.php) на [Gist](https://gist.github.com/) и напишите ссылу здесь. Только уберите параметры подключения к базе.
У вас запущена cron задача для распределения по папкам как написано в Readme ? У вас названия папок с датами такие же как в Readme ?
Более точно смогу сказать, как только увижу конфиг.

**Comment by olejkhar** [comment]
<script src="https://gist.github.com/olejkhar/5db9174e5be2f55c93e9.js"></script>
по паакам раскладывает астер сам, название папок изменил - под свои - и работает -но только текущий день.

**Comment by prog-it** [comment]
Да у вас не правильно сделано.
***Обновил скрипт. Скачайте сктрипт заново и настройте.***

Поставьте также в конфиге `$system_storage_format = 4;`, должно работать как вам надо.
Если все работает, отпишитесь.

**Comment by olejkhar** [comment]
Да закинул и настроил заново, все заработало, сначала правда не воспроизводилось, у меня php 5.1 и мне пришлось закоментировать namespase sendfile, и теперь все ок. СПАСИБО!
