### ISSUE TITLE
Уязвимость в dl.php унаследованная от ACDR дает скачать любой файл с сервера

### ISSUE THREAD

**Issue by vushtenko** [prog-it/Asterisk-CDR-Viewer-Mod#62]
http://SERVER/PATH/dl.php?f=Li4vLi4vLi4vLi4vLi4vLi4vZXRjL2FzdGVyaXNrL3NpcC5jb25m 
где в base64 закодировано ../../../../../../etc/asterisk/sip.conf - отдает его без вопросов!

P.S. в Оригинальном ACDR я уже автора потормошил, он исправил.

**Comment by prog-it** [comment]
Спасибо. Будет исправлено.

**Comment by sardigital** [comment]
пароль спросил перед сливом, не особо то и опасно

**Comment by prog-it** [comment]
В принципе верно, тем более что Viewer предполагается для локального пользования, т.е. чтобы не был доступен из внешки. Но лучше исправить)

**Comment by vushtenko** [comment]
Пароль спросил - потому что включена HTTP авторизация. Но никто не мешает проект выложить без HTTP авторизации или если по каким то причинам она сломалась - это дырка :)

**Comment by vushtenko** [comment]
Кстати о HTTP-авторизации: 
```
if ( strlen($cdr_user_name) > 0 ) {
header('HTTP/1.1 403 Forbidden');
exit;
}
```
это имеет смысл при == 0, а так спокойно пропускает, т.к. в load.php тоже ошибка, и это вот:

```
# Авторизация
$cdr_user_name = getenv('REMOTE_USER');
if ( strlen($cdr_user_name) > 0 ) {
```
отрабатывает при отключенной авторизации спокойно не заходя в этот if идет дальше и не требует ее :)

**Comment by sardigital** [comment]
хм, таки кусок SSO, интересно...

**Comment by vushtenko** [comment]
> хм, таки кусок SSO, интересно...
не знаю, что вы имели ввиду, но я бы в load.php добавил проверку на $_SERVER['AUTH_TYPE'] == "Basic" и если нет то принудительно ее требовать.

**Comment by prog-it** [comment]
**Исправлено в версии 2.6.1.**

> Кстати о HTTP-авторизации...

Тут все верно. Немного другая логика. Это работает при включенной HTTP-авторизации (добавлено пояснение в конфиг).
