### ISSUE TITLE
Баг с плеером.

### ISSUE THREAD

**Issue by leksnsk** [prog-it/Asterisk-CDR-Viewer-Mod#63]
Добрый день.
Обнаружил такой баг. Создал два пользовательских конфига  config-record.php  и  config-norecord.php 
В config-norecord.php указана директория в которой нет записей 'monitor_dir' => '/home', Идея в том что пользователи которые могут смотреть cdr, но не могут слушать записи попадают  на страницу статистики через 
 config-norecord.php.  Все работает ровно до попытки зайти на config-record.php. Кнопка прослушивания есть, но при нажатии плеер запускается и пишет "нет файла".  Хотя  в файле config-record.php  директория указана другая 'monitor_dir' => '/var/calls',

**Comment by prog-it** [comment]
Проверил, есть такой баг. Берет параметры из файла config.php, если попытаться скачать/воспроизвести запись. На днях будет исправлено. Спасибо.

**Comment by prog-it** [comment]
Исправлено в версии 2.6.1
