### ISSUE TITLE
Проблема с выбором дат 1 числа

### ISSUE THREAD

**Issue by Makioro** [prog-it/Asterisk-CDR-Viewer-Mod#66]
Пользуюсь версией 2.2.4.
Обнаружил баг 1 числа. Если из выпадающего списка выбрать "Вчера", то вместо "с 31 октября по 31 октября" показывает "с 30 сентября по 31 октября". Так же не работает вариант "предыдущая неделя": показывает "с 22 сентября по 29 октября", а должен "с 23 октября по 29"
Попытался разобраться в коде чтоб исправить - не разобрался
Скачал текущую версию 2.6.2 - в ней тот же баг, а также в версии 2.6.2 какая-то фигня с отображением текущих звонков - какой бы период не выбрал, всегда показывает 1-2 звонка, при этом пишет типа "Показаны 1 из 7822, отфильтровано 99 записей" при пустых фильтрах
В связи с последним просьба когда найдёте баг сообщить как исправить чтоб я мог исправить в своей версии 2.2.4
Спасибо

p.s. могли бы вы позакрывать выполненные проблемы? прочел несколько, где описан баг, в конце написано что поправили, но проблема висит открытой

**Comment by prog-it** [comment]
Баг мне известен. Будет исправлен только с введением нового варианта выбора периода дат в виде календаря. Но тут много работы из-за несовместимости стилей с Bootstrap. В ближайшее время займусь этим, но для версии 2.2.4 навряд ли получится что-либо сделать, слишком много изменений.
А что не дает обновиться с версии 2.2.4 до актуальной, если не секрет?
Неактуальные issue постараюсь закрыть.

**Comment by Makioro** [comment]
Как я уже выше написал, с 2.6.2 какая-то непонятная проблема с фильтрами
"Скачал текущую версию 2.6.2 - в ней тот же баг, а также в версии 2.6.2 какая-то фигня с отображением текущих звонков - какой бы период не выбрал, всегда показывает 1-2 звонка, при этом пишет типа "Показаны 1 из 7822, отфильтровано 99 записей" при пустых фильтрах"

**Comment by prog-it** [comment]
Если показывает `Показаны 1 из 7822...`, значит у вас задан параметр в Дополнительных опциях `Кол-во строк` для показа 1.
В 2.6.2 этот баг также присутствует, но с версии 2.2.4 немного улучшено его поведение.

**Comment by Makioro** [comment]
Нет-нет, читайте полный текст "Показаны 1 из 7822, отфильтровано 99 записей"
В дополнительных опциях указано 100 строк. Т.е. интерфейс нашел 7822 записей, хотел показать 100 из них, но по какой-то причине 99 отфильтровал и показал только 1
Причем эта одна может меняться при обновлении странички - обычно когда счетчик звонков увеличивается с поступлением новых. Без каких либо изменений в фильтрах

**Comment by prog-it** [comment]
`отфильтровано 99 записей` - это удаление дублирующихся записей для Asterisk 13+. Корректность работы не возможности проверить, т.к. используется Asterisk 11, хотя должно работать.
Можно удаление дублирующихся записей отключить в конфиге: параметр `duphide` задать 0 (секция display -> main)

**Comment by Makioro** [comment]
Помогло
Похоже некорректно работает удаление дублирующихся записей
Значит обновлюсь когда вспомню где я допиливал под себя 2.2.4 :)

**Comment by Makioro** [comment]
А где можно почитать чейнджлог?

**Comment by prog-it** [comment]
https://github.com/prog-it/Asterisk-CDR-Viewer-Mod/releases

И там ниже кнопка Next.
PS Если бы кто предоставил дамп базы CDR, скажем последние 1000 записей с Asterisk 13+, то было бы проще отладить. А так баг из-за запроса select с параметром LIMIT.

**Comment by Makioro** [comment]
Спасибо за ссылку
Так же есть проблема в новой версии: в полях "Входящий канал" и "Исходящий канал" просто указано "SIP", в старой версии пишет "SIP/user"

**Comment by prog-it** [comment]
Это не баг, не все настройки смотрели в конфиге. Нужный вам параметр `full_channel` задать 1 (секция display -> main). Отпишитесь, если все правильно работает.

**Comment by Makioro** [comment]
даже не представляю для чего нужно скрывать канал

> PS Если бы кто предоставил дамп базы CDR, скажем последние 1000 записей с Asterisk 13+, то было бы проще отладить. А так баг из-за запроса select с параметром LIMIT.

если номера заменить на фиктивные всё ещё будет возможность протестировать?

**Comment by prog-it** [comment]
Да, будет.

**Comment by prog-it** [comment]
> даже не представляю для чего нужно скрывать канал

Сейчас есть всплывающие подсказки для показа полной информации, экономия места на экране.

**Comment by Makioro** [comment]
куда отправить дамп?
правда я сделал 1000 записей, а потом поудалял оттуда исходящие, внутренние звонки, всякие логины в очередь, паузы...  осталось 635 :)

**Comment by Makioro** [comment]
Из сообщения может кто угодно скачать? На случай если я не удалил какие-то лишние данные лучше отправлю почтой

**Comment by prog-it** [comment]
Написал вам на почту.

**Comment by Makioro** [comment]
Ещё один баг с выбором дат в последней версии
В других браузерах не проверял, но в хроме сохраняется значение поля "Выбрать период..."
Например, вчера я открывал страничку с детализацией и выбирал "Сегодня", там выбрались даты с 4 по 4 ноября. Сегодня я снова запускаю браузер и открываю вчерашние вкладки, а там осталось "с 4 по 4 ноября" и значение поля "Сегодня". Я открываю выпадающий список, выбираю "Сегодня", но ничего не происходит, т.к. в скрипте "onChange", а оно не произошло. Выходит, чтобы выбрать сегодня мне нужно сначала выбрать любой другой элемент списка, а потом "Сегодня"
В версии 2.2.4 эта проблема решена элементарно: при нажатии "Найти" значение поля "Выбрать период..." сбрасывается к значению "Выбрать период..."

**Comment by prog-it** [comment]
Постараюсь сегодня исправить и выложить.

**Comment by prog-it** [comment]
> Ещё один баг с выбором дат в последней версии...

Исправлено в версии 2.6.3, пробуйте.

**Comment by prog-it** [comment]
Исправлено в версии 2.6.4
