### ISSUE TITLE
Неверный статус звонка по сути

### ISSUE THREAD

**Issue by lDemonik** [prog-it/Asterisk-CDR-Viewer-Mod#67]
Если звонок приходит на астериск, потом абонент попадает в очередь и там уже кладет трубку, не дождавшись ответа оператора то статус в CDR Viewer отображается как "Отвечено". По факту был Answer звонка и в очередь попало, но по сути абонент бросил трубку и статус должен быть "Не отвечен". 
В CDR я могу это отследить т.к. нет ИСХ.Канала и записи разговора звонка, а вот администратор уже нет, и отчеты не построить по "не отвеченным".
Как это можно поправить?

**Comment by prog-it** [comment]
Тут нужно править свой диалплан и писать в отдельную колонку правильный статус звонка. Возможно, можно обойтись триггером в базе, который будет это делать.

В новых версиях CDR Viewer будет добавлена работа с колонками произвольного имени, т.е. можно будет выводить и строить отчеты не из колонки disposition, а из колонки со своим именем, допустим, disposition_true.

**Comment by lDemonik** [comment]
Т.е. добавлять в БД свою колонку и в неё писать статус звонка из диалплана астериска. И в дальнейшем строить отчеты по этой колонке? В будущих версиях...

**Comment by prog-it** [comment]
Да, Asterisk не дает править свои CDR поля. Можно сделать с триггером в базе. В диалплане писать правильный статус в отдельную колонку disposition_true, а триггер в базе будет реагировать на событие insert и заменять статус в колонке disposition.
Есть пример триггера для правильного dst (Куда звонили). В самом низу страницы: https://github.com/prog-it/Asterisk-CDR-Viewer-Mod/blob/master/docs/mysql_cdr.sql

**Comment by lDemonik** [comment]
Большое Вам спасибо. У Вас отличный продукт. Так держать!

**Comment by lDemonik** [comment]
Сделали триггер в базе
BEFORE
INSERT
Сам триггер:
```
BEGIN
	IF (NEW.dstchannel IS NULL) THEN 
		SET NEW.disposition_true = "NO_ANSWERED";
    ELSE
    	SET NEW.disposition_true = "ANSWERED";
	END IF;
END
```
Работает, пишет в поле disposition_true правильные ANSWERED и NO_ANSWERED
