### ISSUE TITLE
Интерфейс показывает, что файла записи нет. 

### ISSUE THREAD

**Issue by clangendum** [prog-it/Asterisk-CDR-Viewer-Mod#7]
Добрый день.
Постарался максимально точно настроить, как описано в документации. 
1. Файлы mp3 в нужной структуре есть, даже в 3-х вариантах сразу (1, 2, 3/4), что бы исключить проблему на этом этапе. 
2. Файл конфигурации https://gist.github.com/clangendum/1485c85d92b9de0d69b1.
3. Запись в MySQL идет корректная, в поле filename, сверял названия, все ок.
4. В режиме отладки все ок, ошибок нет, только Notice: Undefined index...

Вообще не понимаю куда копать. Подскажите, пожалуйста, хотя бы вектор.
Заранее большое спасибо.

![cdr](https://cloud.githubusercontent.com/assets/15278855/10711039/9629508e-7a78-11e5-91d7-469dc0900373.png)
![ftp](https://cloud.githubusercontent.com/assets/15278855/10711040/964d6fdc-7a78-11e5-8d38-14d13b688680.png)

**Comment by prog-it** [comment]
1. У вас все файлы и папки с датами (2015 и т д) точно лежат в /var/calls ?
2. Файлы за предыдущие даты тоже не отображаются, допустим 2-3 дня назад ?

**Comment by clangendum** [comment]
Спасибо за быстрый ответ.
1. Второй раз проверил - да, 100%
2. Только сегодня начал крутить, файлы только за 1 день.

**Comment by prog-it** [comment]
С `$system_storage_format = 1;` файлы за сегодня должны находиться в **/var/calls**, не /var/calls/2015. Файлы за предудыщие даты в папках в соответствии с датой (/var/calls/2015/...). У вас точно так ?
На скрине видно только папку 2015, сделайте скрин /var/calls также с иерархией папок и файлов.

**Comment by clangendum** [comment]
![ftp2](https://cloud.githubusercontent.com/assets/15278855/10711381/fe43ad46-7a81-11e5-9ddf-b586726a68f5.png)
Да, все верно, у меня одни и те же файлы лежат как в /var/calls, так и в /var/calls/2015/10/24, а так же в /var/calls/2015/2015-10/2015-10-24.

Это для того, что бы исключить на данный момент возможное несогласованные локаций. Потом все будет лежать, где положено, согласно $system_storage_format = 1 или 2

**Comment by prog-it** [comment]
1. Попробуйте поставить, например так `$system_storage_format = 99;`. Что-нибудь изменилось после этого ?
2. В файле /inc/func.inc.php добавьте после строчки `echo $tmpRes;` строчку
`var_dump($rec); var_dump($row);`
После этого скиньте вывод на Gist, только замените номера телефонов. Можно по одному блоку того и того.

**Comment by clangendum** [comment]
1. Есть, никаких изменений.
2. https://gist.github.com/clangendum/98a61ad6fca77e5bb1c7, замечу, что первый файл меньше 10 кб, обнаружил после завершения сборов. Второй около 48 кб.

**Comment by prog-it** [comment]
Вроде бы все верно, но у вас размер файла выдает 0. 
Специально проверил у себя, создал такие же папки по пути /var/calls, проверил все форматы хранения. Все работает.

У вас какие права выставлены на папку /var/calls и остальные в ней, а также файлы?

**Comment by clangendum** [comment]
Стыдно, признаюсь. Не в бровь, а в глаз. Все элементарно, права только у root. Огромное Вам спасибо за труд и низкий поклон помощь!
