### ISSUE TITLE
CDR не читает файл записи из базы.

### ISSUE THREAD

**Issue by dewedent** [prog-it/Asterisk-CDR-Viewer-Mod#70]
Привет, проблемка такая, у нас уже стоял и довольно давно работает астериск 1.8.13.1. Хотел прикрутить уже наконец в CDR, чтобы можно было напрямую скачивать и слушать звонки (раньше просто просмотр был) и файлы писались в gsm, диалплан поменял, теперь все пишется в mp3 в папку /var/calls/ в прочем все по стандарту, пробовал прикрутить к уже созданной базе звонков, не получилось хотя файл записи в таблицу recordingfile пишет, но cdr его не видит. Создал новую базу, уже с типовыми настройками как из мануала, так же не читает файл. Может кто подскажет, уже может сталкивались с таким. В config.php прописал только 'storage_format' => 5 чтобы не городить папки и настройка была более простой. Пробовал создать в mySQL нового пользователя со всеми правами на таблицу и базу.

**Comment by prog-it** [comment]
Нужна дополнительная информация, чтобы разобраться.
Выложите:
- полный файл config.php без параметров подключения к базе
- скрин на котором бы было видно имена полей в базе и содержимое хотя бы одного поля полностью. Номера телефонов можно скрыть
- полное имя файла из папки /var/calls/

Попробуйте в файле index.php раскомментировать самую первую строку, будет ли выдавать какие-либо ошибки в веб-интерфейсе. У вас в веб-интерфейсе в колонке "Файл" перечеркнутый значок?

**Comment by dewedent** [comment]
[config.txt](https://github.com/prog-it/Asterisk-CDR-Viewer-Mod/files/1498490/config.txt)
![chrome_2017-11-23_16-04-24](https://user-images.githubusercontent.com/33921215/33165544-ddabbd90-d069-11e7-8e34-feb57398eb91.png)
/var/calls/2017-11-22-17_55-XXXXXXXXX-500.mp3

Строку раскомментировал, ошибок не замечено. Файл да, перечеркнутый.
![chrome_2017-11-23_16-15-18](https://user-images.githubusercontent.com/33921215/33165567-e85b622c-d069-11e7-8bda-d7031e81abe8.png)

**Comment by dewedent** [comment]
Прошу прощения, я нашел проблему. в Диалплане упустил один важный пункт как UNIQUEID/
`exten => s,n(mp3),Set(fname=${UNIQUEID}-${STRFTIME(${EPOCH},,%Y-%m-%d-%H_%M)}-${ARG1}-${ARG2});`
и все появилось.

**Comment by prog-it** [comment]
ОК.
