### ISSUE TITLE
Нестандартное хранение файлов записей

### ISSUE THREAD

**Issue by Realmagnum** [prog-it/Asterisk-CDR-Viewer-Mod#72]
### Добрый вечер.  
_Спасибо за качественный продукт. )_

У меня по наследству от интегратора хранение файлов записей в формате 
`./2017-12/2017-12-12/in/2017-12-12 18-12-33 (+79155127173 - 74833643002).wav`

Инфо о файле находится в поле `userfield` в таком виде 
_2017-12/2017-12-12/**in**/2017-12-12 18-12-33 (+79155127173 - 74833643002)_
_2017-12/2017-12-12/**out**/2017-12-12 18-17-18 (138 - 89679604593)_
_2017-12/2017-12-12/**int**/2017-12-12 17-49-55 (333 - 331)_
Как посоветуете обыграть в правках исходников такой формат?

**PS.** Менять формат хранения информации если честно не хочется, на свой лад она вполне логичная. 
Но все же, если предложите вариант как это сделать с должной степенью автоматизации - буду благодарен.

**PSS**. Хотелось бы конечно, чтобы уже в коде был предусмотрен подобный вариант когда `путь+имя файла` хранится в одном поле. )

**Comment by prog-it** [comment]
Можете привести пример хранения для кого-нибудь одного файла.
- Полный путь к файлу от корня диска
- Полное содержимое поля `userfield` для этого файла

Это нужно для понимания, как лучше сделать. Возможно, добавлю новый вариант хранения файлов.

**Comment by Realmagnum** [comment]
Ну вроде как сам разобрался(звонок другу :). Работает.
**functions.php.patch**
```
--- /var/www/localhost/htdocs/Asterisk-CDR-Viewer-Mod/inc/functions.php>2017-12-05 16:55:59.000000000 +0300
+++ /var/www/localhost/htdocs/cdrstatmod/inc/functions.php<---->2017-12-12 22:41:14.000000000 +0300
@@ -118,6 +118,10 @@
  		$rec['filename'] = "$mycalldate_y/$mycalldate_ym/$mycalldate_ymd/$recorded_file";
  } else if ( Config::get('system.storage_format') === 4 ) {
		$rec['filename'] = "$mycalldate_y/$mycalldate_m/$mycalldate_d/$recorded_file";
+ } else if ( Config::get('system.storage_format') === 5 ) {
+		$rec['path']=substr($recorded_file,0,strrpos($recorded_file,"/")+1);
+		$recorded_file=substr($recorded_file,strrpos($recorded_file,"/")+1,strlen($recorded_file)-strrpos($recorded_file,"/"));
+		$rec['filename']='monitor/'.$rec['path'].$recorded_file.'.wav';
  } else {
		$rec['filename'] = $recorded_file;
  }
```

Спасибо.

**Comment by Realmagnum** [comment]
**В userfield**: `2017-12/2017-12-12/in/2017-12-12 18-12-33 (+79155127173 - 74833643002)`
**Файл**: `/home/asterisk/monitor/2017-12/2017-12-12/in/2017-12-12 18-12-33 (+79155127173 - 74833643002).wav`

**Comment by prog-it** [comment]
Постараюсь добавить ваш вариант в ближайшее время.

**Comment by prog-it** [comment]
Добавлено в версии 2.6.4
