### ISSUE TITLE
Нет кнопки на воспроизведения файла аудиозаписи.

### ISSUE THREAD

**Issue by alexlutor** [prog-it/Asterisk-CDR-Viewer-Mod#73]
Добрый день. Подскажите пожалуйста, не могу победить кнопку воспроизведения))
конфиг почти по умолчанию
[config.txt](https://github.com/prog-it/Asterisk-CDR-Viewer-Mod/files/1565829/config.txt)

в диалплане поправил, чтобы писал подобное 1513526441.105.mp3(читал предыдущие посты)
[dialplan.txt](https://github.com/prog-it/Asterisk-CDR-Viewer-Mod/files/1565827/dialplan.txt)

[лог Asterisk.txt](https://github.com/prog-it/Asterisk-CDR-Viewer-Mod/files/1565828/Asterisk.txt)
думал, что не хватает прав на изменения добавлял 777.

![image](https://user-images.githubusercontent.com/34627233/34081593-f68d080e-e370-11e7-97ce-bacd5ad6428d.png)

![image](https://user-images.githubusercontent.com/34627233/34081603-1a2e2108-e371-11e7-86ab-575fa5dcfb14.png)
Страничка работает нормально, кроме воспроизведения. 
Пока не понимаю, почему не работает? Подскажите пожалуйста.

**Comment by prog-it** [comment]
Должно работать, проверил у себя такой формат хранения записей.
- В базе точно есть заполненная колонка `calldate`, на скрине не видно?
- Попробуйте поставить права 777 на папки: 2017, 12, 17
- Файлы mp3 не нулевого размера? (хотя, навряд ли)

**Comment by alexlutor** [comment]
Спасибо за ответ. 
Дата пишется, скрин приложил.
![image](https://user-images.githubusercontent.com/34627233/34082732-612fe262-e385-11e7-8979-0cd088e1dafe.png)

Справку читал, про размер видел параметр. Файлы не пустые.
![image](https://user-images.githubusercontent.com/34627233/34082742-99951ff0-e385-11e7-8a82-fd9d0f4a63b1.png)

выставил права 777, не помогло. 
Еще заметил пока странную особенность, в wav не пишите в базу. Особо с этим не занимался, так как планировал сразу писать в mp3.
Даже пока не понимаю в какую сторону идти?

в файле extensions.conf указаны настройки
[globals]
RECORDING=1;
DIR_RECORDS=/var/calls/;

в файле cdr_mysql.conf указаны настройки
[columns]
alias realdst => realdst
alias remoteip => remoteip
alias start => calldate
alias filename => filename

Как понимаю все эти настройки выставлены верно? Иначе в базе не было бы записей.

**Comment by prog-it** [comment]
Поставьте права 0755 на все папки: var, calls, 2017, 12, 17
А также на все файлы в папке: 17

Настроено все верно, у какой-то из папок нет X прав на выполнение. Скорее всего, у папки calls.

**Comment by alexlutor** [comment]
Добрый день! Права на calls и все директории, в том числе до файла поставил 0777. Результата не дало.
![image](https://user-images.githubusercontent.com/34627233/34094670-f5cb7d7c-e3ef-11e7-9a53-69434380c791.png)
Может какое-то логирование можно сделать?

**Comment by prog-it** [comment]
Попробуйте в файле `index.php` раскомментировать самую первую строчку, будет ли выдавать какие-либо ошибки.

**Comment by alexlutor** [comment]
Добрый день. Раскомментировал, стало интереснее искать ошибки.
1) поправил временную зону /etc/php.ini (centos)
date.timezone = "как указано в системе"
Стало меньше ошибок.
2) Но остались последние
![image](https://user-images.githubusercontent.com/34627233/34118298-2127a0ae-e440-11e7-8945-da3ceb3c1d4c.png)
----------------------------------------------------------------------------------------
Warning: filesize(): stat failed for /var/calls/2017/12/18/1513563152.1.mp3 in /var/www/html/inc/functions.php on line 128
Warning: filesize(): stat failed for /var/calls/2017/12/18/1513563152.1.mp3 in /var/www/html/inc/functions.php on line 148
--------------------------------------
версия php
 php -v
PHP 5.4.16 (cli) (built: Nov 15 2017 16:33:54)
Copyright (c) 1997-2013 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2013 Zend Technologies
---------------------------------------
Поискал в интернете, думал проблема в правах. Но как понимаю не в них.
--------------------------------------------------------------------------------
[root@localhost calls]# ls -l /var/calls/2017/12/17/151352*
-rwxrwxrwx. 1 apache apache 10656 дек 17 17:52 /var/calls/2017/12/17/1513522347.81.mp3
-rwxrwxrwx. 1 apache apache 13536 дек 17 18:32 /var/calls/2017/12/17/1513524759.87.mp3
-rwxrwxrwx. 1 apache apache  8640 дек 17 18:34 /var/calls/2017/12/17/1513524862.90.mp3
-rwxrwxrwx. 1 apache apache 31680 дек 17 18:37 /var/calls/2017/12/17/1513525020.93-2017-12-17-18_37-100-101.mp3
-rwxrwxrwx. 1 apache apache  9216 дек 17 18:38 /var/calls/2017/12/17/1513525092.96-2017-12-17-18_38-101-100.mp3
-rwxrwxrwx. 1 apache apache 86112 дек 17 18:53 /var/calls/2017/12/17/1513525953.99.mp3
-rwxrwxrwx. 1 apache apache 38304 дек 17 18:54 /var/calls/2017/12/17/1513526068.102.mp3
-rwxrwxrwx. 1 apache apache 19584 дек 17 19:00 /var/calls/2017/12/17/1513526441.105.mp3
---------------------------------------------------------------------------------------------------

**Comment by prog-it** [comment]
Скорее всего это из-за папки /var, в ней для php недоступен filesize.
Попробуйте переместить (или скопировать) папку calls в home, т.е. будет /home/calls, права на папки чтобы также были 0755. И поправить путь в конфиге, если заработает, отпишитесь. Поправлю путь по умолчанию в скрипте, чтобы потом не было таких проблем.

**Comment by alexlutor** [comment]
"дело было не в бобине..." (c).
Добрый день.
Первоначально закинул файлы записей в /var/www/calls - воспроизведение файлов заработало.

Нашел причину, из за которой не было прав доступа к файлам.
Проблема была в SELinux, не верное указал в конфиге. Параметр на отключения стоял ошибочный, хотя я считал что всё работает. Тут моя ключевая ошибка, так как я не проверил его.
Проверить статус SELinux в centos 7
cat /usr/sbin/sestatus
Ваш комментарий :
"Попробуйте в файле index.php раскомментировать самую первую строчку, будет ли выдавать какие-либо ошибки."
помог найти ошибку. Спасибо))

**Comment by prog-it** [comment]
Отлично.
