### ISSUE TITLE
Asterisk 13 и выше

### ISSUE THREAD

**Issue by brestows** [prog-it/Asterisk-CDR-Viewer-Mod#77]
Добрый день, 
Хотел бы попросить поправить работу, со схемой БД так как у Asterisk 13 и выше схема изменилась, столбца calldate больше нет, он разбит на столбцы start и end.

**Comment by Realmagnum** [comment]
Я бы попросил, чтобы была возможность выбора такого режима, у меня к примеру 1.8.15 используется.

**Comment by prog-it** [comment]
Посмотрим, что можно сделать.

**Comment by belko-nsk** [comment]
Есть изменения по топику?

**Comment by prog-it** [comment]
Изменений в CDR Viewer вносить не требуется. Для того, чтобы корректно работало с Asterisk 13+, нужно создать алиас столбца "start":  `alias start => calldate`. А также в базе создать столбец "calldate".
В новой версии в Readme будет добавлено пояснение по этому поводу, выйдет на днях.

**Comment by hiveliberty** [comment]
Я юзаю давно уже с 13-й версией, но как-то, подобные альясы, я на автомате внёс в конфиг астериска.
В общем, с данной "проблемой" не сталкивался и не думаю, что это может стать хоть сколько-нибудь проблемой для тех, кто работает с астериском.

**Comment by prog-it** [comment]
Добавлено пояснение в файл справки в версии 2.6.4
