### ISSUE TITLE
Выбрать сразу несколько номеров

### ISSUE THREAD

**Issue by chimera8086** [prog-it/Asterisk-CDR-Viewer-Mod#79]
Добрый день.
Есть необходимость делать выборку сразу по нескольким произвольным номерам. Допустим куда звонили 100, 101 и 102. Есть ли возможность их разом перечислить в поле "кто звонил" и если есть то в каком формате: 100,101,102 или 100&101&102 и т.д. ?

**Comment by prog-it** [comment]
Есть. На днях выйдет новая версия, в которой все подробно расписано.

Цитата из нового Readme:
### Регулярные выражения

В фильтрах поиска: "Кто звонил", "Куда звонили", "DID (если есть)" можно использовать регулярные выражения Asterisk.

Если значение в одном из этих полей начинается на символ `_`, то это интерпретируется как шаблон поиска.

В шаблонах поиска некоторые символы имеют следующие значения:

- **X** - любая цифра от 0 до 9
- **Z** - любая цифра от 1 до 9
- **N** - любая цифра от 2 до 9
- **[1235-9]** - любая цифра в скобках (в этом примере: 1,2,3,5,6,7,8,9)
- **.** - соответствует любому символу. (например: _9011. совпадает со любым номером, который начинается с 9011, исключая сам номер 9011)

#### Примеры

- **_ZXXXXXX** - соответствует семизначному городскому номеру
- **_79XXXXXXXXX** - соответствует Российскому мобильному номеру

В одно поле поиска (например: "Кто звонил") можно ввести несколько регулярных выражений, разделенных *запятой*.
Благодаря этому можно осуществить поиск сразу по нескольким номерам (например в поле "Кто звонил")

#### Примеры

- _1001, _1002, _1003
- _100., _100Z, _1005
- _1XXX, _562., _.0075, _2XXN

**Comment by Realmagnum** [comment]
Шикарно, спасибо!

**Comment by chimera8086** [comment]
Возможно проблема в том, что у меня БД postgresql.
Вставляю строчку в поле: 
"Кто звонил" _100., _100Z, _1005  
выбран вариант "Начинается с  "
 получаю следующую ошибку:

PDO::errorInfo(): Array ( [0] => 42601 [1] => 7 [2] => ОШИБКА: ошибка синтаксиса (примерное положение: "RLIKE") LINE 1: ...:00:00' AND '2018-02-04 23:59:59' AND ( ( src RLIKE '^10... ^ )
