### ISSUE TITLE
Ничего не отображается в поле файл 

### ISSUE THREAD

**Issue by ishumilov83** [prog-it/Asterisk-CDR-Viewer-Mod#80]
Добрый день. Скачал и установил последнюю версию. Поиск работает, но нет иконки для проигрывания файла записи. Файлы хранятся  'monitor_dir' => '/var/spool/asterisk/monitor'
Формат "/var/calls/2015/12/01",    'storage_format' => 4. 'audio_format' => 'wav',  Подскажите где что поправить, всю голову сломал. Заранее спасибо.

**Comment by prog-it** [comment]
Скорее всего, что-то с правами на папки/файлы.
Попробуйте сделать: `chmod -R 0755 /var/spool/asterisk/monitor`

Если не поможет, то нужна дополнительная информация.
- Что конкретно находится в столбце "Файл"
- Приведите полный путь к одному из файлов записи звонков на диске
- У вас в БД есть колонка "filename"? Приведите содержимое этой колонки для одного из файлов
- Что у вас прописано в конфиге в `column_name`?

**Comment by ishumilov83** [comment]
Права прописаны на папку /var/spool/asterisk/monitor были.
Полный путь к файлу /var/spool/asterisk/monitor/2018/02/01/exten-101-102-20180201-143534-1517481334.0.wav
В БД есть колонка recordingfile Содержимое 
+---------------------------------------------------------------------------------------+
| recordingfile                                                                         |
+---------------------------------------------------------------------------------------+
| /var/spool/asterisk/monitor/2018/02/01/exten-101-102-20180201-143534-1517481334.0.wav |
| /var/spool/asterisk/monitor/2018/02/01/exten-101-102-20180201-153938-1517485177.0.wav |
| /var/spool/asterisk/monitor/2018/02/01/exten-101-102-20180201-154009-1517485209.2.wav |
+---------------------------------------------------------------------------------------+
3 rows in set (0.00 sec)
В config.php прописано: 
'column_name' => 'recordingfile',
'monitor_dir' => '/var/spool/asterisk/monitor',
'storage_format' => '4',
'audio_format' => 'wav',
'audio_defconv' => 0,
В cdr_mysql.conf:
[global] 
hostname = localhost
dbname=asteriskcdrdb
table=cdr 
password = ########
user = asteriskcdr
userfield=1
port=3306 
sock=/tmp/mysql.sock
[columns]
alias realdst => realdst
alias recordingfile => recordingfile
;alias start => calldate

**Comment by prog-it** [comment]
Т.е. у вас в колонке "recordingfile" так и есть:` /var/spool/asterisk/monitor/2018/02/01/exten-101-102-20180201-143534-1517481334.0.wav` ?
Должно быть только: `exten-101-102-20180201-143534-1517481334.0.wav`.

Если вам предпочтителен только такой формат, тогда подождите 1-2 дня. Выйдет новая версия с таким вариантом хранения записей звонков.

Также советую раскомментировать: `alias start => calldate`, а также создать в БД колонку "calldate", если ее нет. Без нее будет работать некорректно, не только CDR Viewer.

**Comment by ishumilov83** [comment]
Да в колонке именно так и есть. Буду ждать новую версию.
 А как поменять на нужный формат "exten-101-102-20180201-143534-1517481334.0.wav"?

**Comment by prog-it** [comment]
Нужно выполнить такой запрос:
```
UPDATE cdr SET recordingfile = REPLACE(recordingfile, CONCAT( SUBSTRING_INDEX(recordingfile,'/',8), '/'), SUBSTRING_INDEX(recordingfile,'/',-1));
```

Сначала сохраните дамп таблицы! После отпишитесь.

**Comment by ishumilov83** [comment]
Добрый день. Команду выполнил, ничего не изменилось.
Содержимое recordingfile
----------------+
| recordingfile                                                                                |
+----------------------------------------------------------------------------------------------+
| exten-101-102-20180201-143534-1517481334.0.wavexten-101-102-20180201-143534-1517481334.0.wav |
| exten-101-102-20180201-153938-1517485177.0.wavexten-101-102-20180201-153938-1517485177.0.wav |
| exten-101-102-20180201-154009-1517485209.2.wavexten-101-102-20180201-154009-1517485209.2.wav |
+----------------------------------------------------------------------------------------------+
3 rows in set (0.00 sec)
По моему команда которую вы прислали неверно отработала. Названия файлов задвоились

**Comment by ishumilov83** [comment]
Я поправил запрос:
UPDATE cdr SET recordingfile = REPLACE(recordingfile, CONCAT( SUBSTRING_INDEX(recordingfile,'/',8), '/'), ''); 
Все заработало. Но при новых звонках в колонку пишется прежний путь
/var/spool/asterisk/monitor/2018/02/01/exten-101-102-20180201-143534-1517481334.0.wav
Большое спасибо за помощь.

**Comment by prog-it** [comment]
Чтобы писался новый путь, нужно редактировать диалплан в Asterisk.

**Comment by ishumilov83** [comment]
Добрый день. Перенес все на рабочий сервер. Настройки одинаковые с тестовым. Но почему то в колонке recordingfile пусто. Подскажите где нужно копать?

**Comment by prog-it** [comment]
Скорее всего, не задан алиас в Asterisk: `alias recordingfile => recordingfile`

После этого Asterisk нужно перезапустить. Либо, что-то еще может быть в вашем диалплане.

**Comment by ishumilov83** [comment]
Точно, забыл прописать. Все работает, спасибо.
