### ISSUE TITLE
Несколько значений в фильтре

### ISSUE THREAD

**Issue by Tenshinur** [prog-it/Asterisk-CDR-Viewer-Mod#81]
Вопрос: есть ли возможность задать несколько значений в фильтрах?
К примеру выборка по нескольким номерам.

**Comment by prog-it** [comment]
Скоро выйдет новая версия, там будет все подробно написано.

Пока, смотрите здесь:
https://github.com/prog-it/Asterisk-CDR-Viewer-Mod/issues/79#issuecomment-362220985
