### ISSUE TITLE
billsec в статистике

### ISSUE THREAD

**Issue by SShirinyan** [prog-it/Asterisk-CDR-Viewer-Mod#82]
Подскажите, а как сделать отображение столбца и фильтрацию по billsec? Дефолтно оно отображается только при наведении курсора.

**Comment by prog-it** [comment]
Т.е. вам нужно, чтобы отображались столбцы duration и billsec вместе. Либо был выбор, какой из них показать?
Фильтрацию по billsec тоже можно добавить.

**Comment by SShirinyan** [comment]
Да, нужны оба столбца и фильтр по обоим. Вообще, Ваш апгрейд той cdr-stat, которую я ставил 7 лет назад, сильно впечатляет. Чуточку допилить лимит на пользователей и получим полноценную биллинговую систему. Спасибо!

**Comment by prog-it** [comment]
Новая версия выйдет на днях, будет добавлено.

**Comment by SShirinyan** [comment]
Спасибо!

**Comment by prog-it** [comment]
Добавлено в версии 2,6,4
