### ISSUE TITLE
файл docs/Readme.txt

### ISSUE THREAD

**Issue by Olpag** [prog-it/Asterisk-CDR-Viewer-Mod#85]
Поправьте пример макроса, в этом случае никогда не перейдет ко второй строке:
; MixMonitor
[macro-recording]
exten => s,1,GoToIf($["${RECORDING}" = "1"]?mp3:**no**)
exten => s,n,GoToIf($["${RECORDING}" = "2"]?wav:no)

Надо бы:
exten => s,1,GoToIf($["${RECORDING}" = "1"]?mp3)

**Comment by prog-it** [comment]
Спасибо, будет исправлено.

**Comment by prog-it** [comment]
Исправлено в версии 2.6.4
