### ISSUE TITLE
CSV отчет

### ISSUE THREAD

**Issue by ishumilov83** [prog-it/Asterisk-CDR-Viewer-Mod#86]
Добрый день. Ставлю фильтр, фильтр отработал - пишет Показаны 89 из 2441. Но при экспорте в csv-файл экспортируется только те позиции которые отображены на странице, остальные строки в  файл не попадают.

**Comment by prog-it** [comment]
Опишите подробнее. В любом случае, в CSV файле будет содержаться только то, что отображено на экране.

**Comment by ishumilov83** [comment]
Находит нужных записей 2441, а экспортирует только то что отображено на экране - 89. А хотелось  экспортнуть все что найдено - 2441 запись.

**Comment by prog-it** [comment]
Попробуйте указать в "Дополнительные опции" - Кол-во строк = 3000

**Comment by ishumilov83** [comment]
извиняюсь, этой опции я не заметил :)
спасибо
