### ISSUE TITLE
CDR mask XXX

### ISSUE THREAD

**Issue by skorotysh** [prog-it/Asterisk-CDR-Viewer-Mod#87]
Добрый день, подскажите пожалуйста, могу ли я в текущей версии CDR сделать группировку, пира например с номером 810 и указать "Куда звонили" указать маску например чтобы не выводило 3-4  значные номера по маске XXX или XXXX. (Например 802, 411, и 1002 пир)
Смысл в том чтобы отделить исходящие номера от внутренних по шаблону.
Спасибо.

**Comment by prog-it** [comment]
Можно использовать регулярные выражения, как в синтаксисе Asterisk. В одном поле можно использовать несколько регулярных выражений через запятую. 

Например: `_1XX,_20X`

**Comment by skorotysh** [comment]
Спасибо, работает. 
_s,_1XX,_2XX
В моих тестах не было _ , пробовал через 2XX не работало

**Comment by skorotysh** [comment]
Только может в доку добавить)

**Comment by prog-it** [comment]
В новой версии Readme это уже есть, скоро будет выложено.
