### ISSUE TITLE
Изменить тип графика

### ISSUE THREAD

**Issue by dmitrii507** [prog-it/Asterisk-CDR-Viewer-Mod#89]
При генерации отчета, и если отметить чекбокс график, то показывает график по Куда звонили, можно ли его сменить на did например?

**Comment by prog-it** [comment]
Попробуйте выбрать: Группировать по -> DID.

**Comment by dmitrii507** [comment]
Группирую по дид а он всёравно график по Куда звонил показывает.

**Comment by dmitrii507** [comment]
По дням график есть, только при выборе по did отображает не did а куда звонили.

**Comment by dmitrii507** [comment]
А нужен как раз по did

**Comment by prog-it** [comment]
Ошибка найдена в шаблоне. Постараюсь в выходные выложить исправленную версию. Будет работать также с группировкой.

**Comment by dmitrii507** [comment]
Пока что не получилось поправить?

**Comment by prog-it** [comment]
Проверьте обновление сегодня вечером.

**Comment by prog-it** [comment]
Исправлено в версии 2.6.4
