### ISSUE TITLE
Фильтрация и подсчет

### ISSUE THREAD

**Issue by SShirinyan** [prog-it/Asterisk-CDR-Viewer-Mod#91]
В фильтрах выставляю звонки длительностью более 1 сек, но на отображении это не сказывается никак. 
Создал тариф, в списке вроде всё указывается, но в "Расход денежных средств" данные не сливаются.

**Comment by prog-it** [comment]
Фильтр "Длительность" работает правильно, нужно обязательно указывать максимальную длительность звонка. Например: 1 - 9999.
-  Приведите пример CSV файла с тарифами
- В файл `my_callrates.php` вносили какие изменения? Возможно, в нем необходимо подправить SQL запросы под свой диалплан.

**Comment by prog-it** [comment]
В новой версии будет возможность не указывать максимальную длительность звонка.

**Comment by SShirinyan** [comment]
`2,1.00,Город,m,0.01
7,1.00,Город,m,0.01

8800,0.00,Бесплатно,m

89,1.98,Россия моб,m

8,0.99,Россия гор,m

8495,0.00,Столицы,m
8499,0.00,Столицы,m
8812,0.00,Столицы,m
235,0.3,Чад,m
`
В php изменений не вносил

**Comment by SShirinyan** [comment]
Поправил php. Всё работает! Спасибо!
