### ISSUE TITLE
Не воспрозводятся записи

### ISSUE THREAD

**Issue by vanokg** [prog-it/Asterisk-CDR-Viewer-Mod#93]
Вместо кнопи плей перечеркнутый значек.

![index](https://user-images.githubusercontent.com/3435030/39239146-dc873056-48a1-11e8-8885-741916d39ad2.png)

У меня была старая версия Asterisk CDR viewer ( v.1.0.8 )
Я поставил рядом эту версию, поправил конфиги, он к базе подключился записи из базы увидел, а вот сами аудио файлы походу нет, подскажите пожалуйста куда смотреть.

сами аудио файлы лежат в /home/records без дополнительных каталогов.

в 		### Формат хранения файлов записей Asterisk
выбирал все варианты, ни какой не работает.

и я что то не понял как включить Basic Auth, вроде сделал всё как в инструкции а он всёравно не запрашивает логин\пароль.

**Comment by prog-it** [comment]
Скорее всего, у вас в БД отсутствует колонка `filename`. в которой содержится имя файла с записью звонка.
Нужно соответствующим образом настроить Asterisk. чтобы он записывал в эту колонку имя файла, а также предварительно ее создать в БД. Подробнее в файле справки.

Какой у вас сервер? Для применения изменений сервер необходимо перезапустить.

**Comment by vanokg** [comment]
Я нашел для себя вариант решения проблемы.

исправил в конифгах
в файле
inc/functions.php
`                $rec['filename'] = $recorded_file;`
на
`                $rec['filename'] = $recorded_file.'.'.$tmp['system_audio_format'];`

И всё работает, спасибо огромногое за ваши старания!!!

**Comment by vanokg** [comment]
Я извиняюсь, а можно ли как-нибудь добавить возможно сортировки.
Возможно ли сделать так что бы при выборе чек бокса отображались только звонки у которых нет записи?

**Comment by vanokg** [comment]
У меня получается проблема в том, что у меня нет очереди среди операторов, при поступлении звонка, он приходит всем одновременно, и когда один берет трубку, то у остальных фиксируется как пропущенный, но показывает что есть запись разговора (показывает запись того кто взял трубку), вот, я хотел бы отделить реально пропущенные (когда никто не ответил) от таких.
Идей к сожалению как это сделать кроме как выбрав пункт "Показать все без записи" у меня нет(

**Comment by vanokg** [comment]
Всё разобрались, наши разрабы немного адаптировали для нашего случая, спасибо вам огромногое за ваши старания!!!
