### ISSUE TITLE
Не корректная запись номера в базу

### ISSUE THREAD

**Issue by thicking** [prog-it/Asterisk-CDR-Viewer-Mod#95]
Здравствуйте, проблема у меня такая, при звонке в транк, приходится подменять номер звонящего, на номер присвоенный транку на стороне провайдера. Из-за этого, в базу пишется не номер абонента, а номер транка.

пример extensions.conf

exten = _89XXXXXXXXX, 1, Macro(recording,${CALLERID(num)},${EXTEN})
exten = _89XXXXXXXXX, n, Set(CALLERID(num)=221) 
exten = _89XXXXXXXXX, n, Dial(SIP/${EXTEN}@trunk-mts,30)
exten = _89XXXXXXXXX, n, Playback(vm-nobodyavail)
exten = _89XXXXXXXXX, n, Hangup()

пример статистики
[http://prntscr.com/jl7nip](http://prntscr.com/jl7nip)

**Comment by prog-it** [comment]
Может стоит не подменять номер...
Попробуйте `Set(CALLERID(ANI-all)=нужный_номер);`, чтобы в статистику записывался тот номер, который необходим.

**Comment by thicking** [comment]
Сделал так:
exten = _89XXXXXXXXX, 1, Macro(recording,${CALLERID(ANI-all)},${EXTEN})
exten = _89XXXXXXXXX, n, Dial(SIP/${EXTEN}@trunk-mts,,f(221),30)
exten = _89XXXXXXXXX, n, Hangup()
Все ок
