### ISSUE TITLE
Не отображает соединение после неуправляемого перевода

### ISSUE THREAD

**Issue by Asteriskdb** [prog-it/Asterisk-CDR-Viewer-Mod#98]
У нас запись организована с помощью функции U, для того чтобы писался и перевод звонка тоже.
Строчка из extension.conf:
`same => n,Dial(${GR_OFFICE},60,U(recording,${CALLERID(num)},${EXTEN}))`

При неуправляемом переводе id звонка не меняется и в базе данных две строчки с одним uniqueid, но с разными filename (обе записи присутствуют в каталоге). При просмотре данный скрипт отображает только одно соединение, соответственно, невозможно прослушать вторую запись.

Если поставить 'duphide' => 0 в файле config.php, то обе записи становятся доступны, но отображаются вообще все звонки, в том числе и неотвеченные, что тоже неудобно.

**Comment by Asteriskdb** [comment]
Решил вопрос изменением строчки 361 файла index.php 
с
`$superresult[$val['uniqueid'].'-'.$val['disposition']] = $val;`
на
`$superresult[$val['uniqueid'].'-'.$val['disposition'].str_replace(' ','',$val['filename'])] = $val;`

Если решение верное, то хотелось бы его внести в скрипт, поскольку я регулярно ставлю обновления. Текущая версия у меня 2.6.4.

**Comment by prog-it** [comment]
Протестировать полноценно нет возможности, т.к. используется Asterisk 11. По идее, решение верное. Будет добавлено в ближайшей версии.

**Comment by prog-it** [comment]
Можете скинуть пример из базы, чтобы лучше понять.
Т.е. нужно полное содержимое нескольких строк с такой ситуацией из базы, номера телефонов можно заменить на *. Нужно понять, в чем конкретно различие в имени файла.

**Comment by Asteriskdb** [comment]
Вот [тут](https://yadi.sk/d/fWhMzsYz3Zhh8q) дамп трех строчек базы данных как раз с такой ситуацией. Мы используем дополнительное поле checked - его можно удалить.

**Comment by prog-it** [comment]
Проверил. Все работает корректно, пока оставим как есть.
Как сделано у вас не подходит, частный случай. Имя файла учитывать нельзя, иначе дубликаты вообще удаляться не будут. У вас удаляются, потому что для "NO ANSWER" имя файла пустое, а может быть, например, "none", тогда дубликаты останутся.

**Comment by prog-it** [comment]
В новой версии исправлено удаление дублирующихся записей в зависимости от сортировки.
Но, в вашем случае, все равно придется вносить изменения (для новой версии):
```
$duph_filtered[$row['uniqueid'].'-'.$row['disposition'].trim($row[Config::get('system.column_name'))]] = $row;
```

**Comment by Asteriskdb** [comment]
Спасибо за подсказку. Да и вообще за классную программу.
